// Code generated by compschema uniongen. DO NOT EDIT.

package openairesponses

import (
	"encoding/json"
	"fmt"
)

// Annotation is a sealed interface for oneOf union.
// Discriminated by "type" field.
type Annotation interface {
	isAnnotation()
}

func (*FileCitationBody) isAnnotation() {}
func (*URLCitationBody) isAnnotation()  {}
func (*FilePath) isAnnotation()         {}

// UnmarshalAnnotation unmarshals JSON into the correct Annotation variant
// based on the "type" discriminator field.
func UnmarshalAnnotation(data []byte) (Annotation, error) {
	var disc struct {
		D string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.D {
	case "file_citation":
		var val FileCitationBody
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "url_citation":
		var val URLCitationBody
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "file_path":
		var val FilePath
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	default:
		return nil, fmt.Errorf("unknown type %q for Annotation", disc.D)
	}
}

// CodeInterpreterToolOutput is a sealed interface for oneOf union.
// Discriminated by "type" field.
type CodeInterpreterToolOutput interface {
	isCodeInterpreterToolOutput()
}

func (*CodeInterpreterTextOutput) isCodeInterpreterToolOutput() {}
func (*CodeInterpreterFileOutput) isCodeInterpreterToolOutput() {}

// UnmarshalCodeInterpreterToolOutput unmarshals JSON into the correct CodeInterpreterToolOutput variant
// based on the "type" discriminator field.
func UnmarshalCodeInterpreterToolOutput(data []byte) (CodeInterpreterToolOutput, error) {
	var disc struct {
		D string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.D {
	case "logs":
		var val CodeInterpreterTextOutput
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "files":
		var val CodeInterpreterFileOutput
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	default:
		return nil, fmt.Errorf("unknown type %q for CodeInterpreterToolOutput", disc.D)
	}
}

// ComputerAction is a sealed interface for oneOf union.
// Discriminated by "type" field.
type ComputerAction interface {
	isComputerAction()
}

func (*Click) isComputerAction()       {}
func (*DoubleClick) isComputerAction() {}
func (*Drag) isComputerAction()        {}
func (*KeyPress) isComputerAction()    {}
func (*Move) isComputerAction()        {}
func (*Screenshot) isComputerAction()  {}
func (*Scroll) isComputerAction()      {}
func (*Type) isComputerAction()        {}
func (*Wait) isComputerAction()        {}

// UnmarshalComputerAction unmarshals JSON into the correct ComputerAction variant
// based on the "type" discriminator field.
func UnmarshalComputerAction(data []byte) (ComputerAction, error) {
	var disc struct {
		D string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.D {
	case "click":
		var val Click
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "double_click":
		var val DoubleClick
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "drag":
		var val Drag
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "keypress":
		var val KeyPress
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "move":
		var val Move
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "screenshot":
		var val Screenshot
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "scroll":
		var val Scroll
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "type":
		var val Type
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "wait":
		var val Wait
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	default:
		return nil, fmt.Errorf("unknown type %q for ComputerAction", disc.D)
	}
}

// Filters is a sealed interface for anyOf union.
// Discriminated by "type" field.
type Filters interface {
	isFilters()
}

func (*ComparisonFilter) isFilters() {}
func (*CompoundFilter) isFilters()   {}

// UnmarshalFilters unmarshals JSON into the correct Filters variant
// based on the "type" discriminator field.
func UnmarshalFilters(data []byte) (Filters, error) {
	var disc struct {
		D string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.D {
	case "eq":
		var val ComparisonFilter
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "and":
		var val CompoundFilter
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	default:
		return nil, fmt.Errorf("unknown type %q for Filters", disc.D)
	}
}

// InputContent is a sealed interface for oneOf union.
// Discriminated by "type" field.
type InputContent interface {
	isInputContent()
}

func (*InputTextContent) isInputContent()  {}
func (*InputImageContent) isInputContent() {}
func (*InputFileContent) isInputContent()  {}

// UnmarshalInputContent unmarshals JSON into the correct InputContent variant
// based on the "type" discriminator field.
func UnmarshalInputContent(data []byte) (InputContent, error) {
	var disc struct {
		D string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.D {
	case "input_text":
		var val InputTextContent
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "input_image":
		var val InputImageContent
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "input_file":
		var val InputFileContent
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	default:
		return nil, fmt.Errorf("unknown type %q for InputContent", disc.D)
	}
}

// InputItem is a sealed interface for oneOf union.
// Discriminated by "type" field.
type InputItem interface {
	isInputItem()
}

func (*EasyInputMessage) isInputItem()   {}
func (*Item) isInputItem()               {}
func (*ItemReferenceParam) isInputItem() {}

// UnmarshalInputItem unmarshals JSON into the correct InputItem variant
// based on the "type" discriminator field.
func UnmarshalInputItem(data []byte) (InputItem, error) {
	var disc struct {
		D string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.D {
	case "message":
		var val EasyInputMessage
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "item_reference":
		var val ItemReferenceParam
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	default:
		return nil, fmt.Errorf("unknown type %q for InputItem", disc.D)
	}
}

// ItemResource is a sealed interface for oneOf union.
// Discriminated by "type" field.
type ItemResource interface {
	isItemResource()
}

func (*InputMessageResource) isItemResource()           {}
func (*OutputMessage) isItemResource()                  {}
func (*FileSearchToolCall) isItemResource()             {}
func (*ComputerToolCall) isItemResource()               {}
func (*ComputerToolCallOutputResource) isItemResource() {}
func (*WebSearchToolCall) isItemResource()              {}
func (*FunctionToolCallResource) isItemResource()       {}
func (*FunctionToolCallOutputResource) isItemResource() {}

// UnmarshalItemResource unmarshals JSON into the correct ItemResource variant
// based on the "type" discriminator field.
func UnmarshalItemResource(data []byte) (ItemResource, error) {
	var disc struct {
		D string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.D {
	case "message":
		var v0 InputMessageResource
		if err := json.Unmarshal(data, &v0); err == nil {
			return &v0, nil
		}
		var v1 OutputMessage
		if err := json.Unmarshal(data, &v1); err == nil {
			return &v1, nil
		}
		return nil, fmt.Errorf("no matching variant for type=%q in ItemResource", disc.D)
	case "file_search_call":
		var val FileSearchToolCall
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "computer_call":
		var val ComputerToolCall
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "computer_call_output":
		var val ComputerToolCallOutputResource
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "web_search_call":
		var val WebSearchToolCall
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "function_call":
		var val FunctionToolCallResource
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "function_call_output":
		var val FunctionToolCallOutputResource
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	default:
		return nil, fmt.Errorf("unknown type %q for ItemResource", disc.D)
	}
}

// ModelIdsResponses: skipped (has inline/non-$ref variants)

// ModelIdsShared: skipped (has inline/non-$ref variants)

// OutputContent is a sealed interface for oneOf union.
// Discriminated by "type" field.
type OutputContent interface {
	isOutputContent()
}

func (*OutputTextContent) isOutputContent() {}
func (*RefusalContent) isOutputContent()    {}

// UnmarshalOutputContent unmarshals JSON into the correct OutputContent variant
// based on the "type" discriminator field.
func UnmarshalOutputContent(data []byte) (OutputContent, error) {
	var disc struct {
		D string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.D {
	case "output_text":
		var val OutputTextContent
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "refusal":
		var val RefusalContent
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	default:
		return nil, fmt.Errorf("unknown type %q for OutputContent", disc.D)
	}
}

// OutputItem is a sealed interface for anyOf union.
// Discriminated by "type" field.
type OutputItem interface {
	isOutputItem()
}

func (*OutputMessage) isOutputItem()      {}
func (*FileSearchToolCall) isOutputItem() {}
func (*FunctionToolCall) isOutputItem()   {}
func (*WebSearchToolCall) isOutputItem()  {}
func (*ComputerToolCall) isOutputItem()   {}
func (*ReasoningItem) isOutputItem()      {}

// UnmarshalOutputItem unmarshals JSON into the correct OutputItem variant
// based on the "type" discriminator field.
func UnmarshalOutputItem(data []byte) (OutputItem, error) {
	var disc struct {
		D string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.D {
	case "message":
		var val OutputMessage
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "file_search_call":
		var val FileSearchToolCall
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "function_call":
		var val FunctionToolCall
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "web_search_call":
		var val WebSearchToolCall
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "computer_call":
		var val ComputerToolCall
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "reasoning":
		var val ReasoningItem
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	default:
		return nil, fmt.Errorf("unknown type %q for OutputItem", disc.D)
	}
}

// ResponseStreamEvent is a sealed interface for anyOf union.
// Discriminated by "type" field.
type ResponseStreamEvent interface {
	isResponseStreamEvent()
}

func (*ResponseAudioDeltaEvent) isResponseStreamEvent()                      {}
func (*ResponseAudioDoneEvent) isResponseStreamEvent()                       {}
func (*ResponseAudioTranscriptDeltaEvent) isResponseStreamEvent()            {}
func (*ResponseAudioTranscriptDoneEvent) isResponseStreamEvent()             {}
func (*ResponseCodeInterpreterCallCodeDeltaEvent) isResponseStreamEvent()    {}
func (*ResponseCodeInterpreterCallCodeDoneEvent) isResponseStreamEvent()     {}
func (*ResponseCodeInterpreterCallCompletedEvent) isResponseStreamEvent()    {}
func (*ResponseCodeInterpreterCallInProgressEvent) isResponseStreamEvent()   {}
func (*ResponseCodeInterpreterCallInterpretingEvent) isResponseStreamEvent() {}
func (*ResponseCompletedEvent) isResponseStreamEvent()                       {}
func (*ResponseContentPartAddedEvent) isResponseStreamEvent()                {}
func (*ResponseContentPartDoneEvent) isResponseStreamEvent()                 {}
func (*ResponseCreatedEvent) isResponseStreamEvent()                         {}
func (*ResponseErrorEvent) isResponseStreamEvent()                           {}
func (*ResponseFileSearchCallCompletedEvent) isResponseStreamEvent()         {}
func (*ResponseFileSearchCallInProgressEvent) isResponseStreamEvent()        {}
func (*ResponseFileSearchCallSearchingEvent) isResponseStreamEvent()         {}
func (*ResponseFunctionCallArgumentsDeltaEvent) isResponseStreamEvent()      {}
func (*ResponseFunctionCallArgumentsDoneEvent) isResponseStreamEvent()       {}
func (*ResponseInProgressEvent) isResponseStreamEvent()                      {}
func (*ResponseFailedEvent) isResponseStreamEvent()                          {}
func (*ResponseIncompleteEvent) isResponseStreamEvent()                      {}
func (*ResponseOutputItemAddedEvent) isResponseStreamEvent()                 {}
func (*ResponseOutputItemDoneEvent) isResponseStreamEvent()                  {}
func (*ResponseReasoningSummaryPartAddedEvent) isResponseStreamEvent()       {}
func (*ResponseReasoningSummaryPartDoneEvent) isResponseStreamEvent()        {}
func (*ResponseReasoningSummaryTextDeltaEvent) isResponseStreamEvent()       {}
func (*ResponseReasoningSummaryTextDoneEvent) isResponseStreamEvent()        {}
func (*ResponseRefusalDeltaEvent) isResponseStreamEvent()                    {}
func (*ResponseRefusalDoneEvent) isResponseStreamEvent()                     {}
func (*ResponseTextAnnotationDeltaEvent) isResponseStreamEvent()             {}
func (*ResponseTextDeltaEvent) isResponseStreamEvent()                       {}
func (*ResponseTextDoneEvent) isResponseStreamEvent()                        {}
func (*ResponseWebSearchCallCompletedEvent) isResponseStreamEvent()          {}
func (*ResponseWebSearchCallInProgressEvent) isResponseStreamEvent()         {}
func (*ResponseWebSearchCallSearchingEvent) isResponseStreamEvent()          {}

// UnmarshalResponseStreamEvent unmarshals JSON into the correct ResponseStreamEvent variant
// based on the "type" discriminator field.
func UnmarshalResponseStreamEvent(data []byte) (ResponseStreamEvent, error) {
	var disc struct {
		D string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.D {
	case "response.audio.delta":
		var val ResponseAudioDeltaEvent
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "response.audio.done":
		var val ResponseAudioDoneEvent
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "response.audio.transcript.delta":
		var val ResponseAudioTranscriptDeltaEvent
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "response.audio.transcript.done":
		var val ResponseAudioTranscriptDoneEvent
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "response.code_interpreter_call.code.delta":
		var val ResponseCodeInterpreterCallCodeDeltaEvent
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "response.code_interpreter_call.code.done":
		var val ResponseCodeInterpreterCallCodeDoneEvent
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "response.code_interpreter_call.completed":
		var val ResponseCodeInterpreterCallCompletedEvent
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "response.code_interpreter_call.in_progress":
		var val ResponseCodeInterpreterCallInProgressEvent
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "response.code_interpreter_call.interpreting":
		var val ResponseCodeInterpreterCallInterpretingEvent
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "response.completed":
		var val ResponseCompletedEvent
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "response.content_part.added":
		var val ResponseContentPartAddedEvent
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "response.content_part.done":
		var val ResponseContentPartDoneEvent
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "response.created":
		var val ResponseCreatedEvent
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "error":
		var val ResponseErrorEvent
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "response.file_search_call.completed":
		var val ResponseFileSearchCallCompletedEvent
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "response.file_search_call.in_progress":
		var val ResponseFileSearchCallInProgressEvent
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "response.file_search_call.searching":
		var val ResponseFileSearchCallSearchingEvent
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "response.function_call_arguments.delta":
		var val ResponseFunctionCallArgumentsDeltaEvent
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "response.function_call_arguments.done":
		var val ResponseFunctionCallArgumentsDoneEvent
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "response.in_progress":
		var val ResponseInProgressEvent
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "response.failed":
		var val ResponseFailedEvent
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "response.incomplete":
		var val ResponseIncompleteEvent
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "response.output_item.added":
		var val ResponseOutputItemAddedEvent
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "response.output_item.done":
		var val ResponseOutputItemDoneEvent
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "response.reasoning_summary_part.added":
		var val ResponseReasoningSummaryPartAddedEvent
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "response.reasoning_summary_part.done":
		var val ResponseReasoningSummaryPartDoneEvent
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "response.reasoning_summary_text.delta":
		var val ResponseReasoningSummaryTextDeltaEvent
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "response.reasoning_summary_text.done":
		var val ResponseReasoningSummaryTextDoneEvent
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "response.refusal.delta":
		var val ResponseRefusalDeltaEvent
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "response.refusal.done":
		var val ResponseRefusalDoneEvent
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "response.output_text.annotation.added":
		var val ResponseTextAnnotationDeltaEvent
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "response.output_text.delta":
		var val ResponseTextDeltaEvent
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "response.output_text.done":
		var val ResponseTextDoneEvent
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "response.web_search_call.completed":
		var val ResponseWebSearchCallCompletedEvent
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "response.web_search_call.in_progress":
		var val ResponseWebSearchCallInProgressEvent
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "response.web_search_call.searching":
		var val ResponseWebSearchCallSearchingEvent
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	default:
		return nil, fmt.Errorf("unknown type %q for ResponseStreamEvent", disc.D)
	}
}

// TextResponseFormatConfiguration is a sealed interface for oneOf union.
// Discriminated by "type" field.
type TextResponseFormatConfiguration interface {
	isTextResponseFormatConfiguration()
}

func (*ResponseFormatText) isTextResponseFormatConfiguration()           {}
func (*TextResponseFormatJsonSchema) isTextResponseFormatConfiguration() {}
func (*ResponseFormatJsonObject) isTextResponseFormatConfiguration()     {}

// UnmarshalTextResponseFormatConfiguration unmarshals JSON into the correct TextResponseFormatConfiguration variant
// based on the "type" discriminator field.
func UnmarshalTextResponseFormatConfiguration(data []byte) (TextResponseFormatConfiguration, error) {
	var disc struct {
		D string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.D {
	case "text":
		var val ResponseFormatText
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "json_schema":
		var val TextResponseFormatJsonSchema
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "json_object":
		var val ResponseFormatJsonObject
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	default:
		return nil, fmt.Errorf("unknown type %q for TextResponseFormatConfiguration", disc.D)
	}
}

// Tool is a sealed interface for oneOf union.
// Discriminated by "type" field.
type Tool interface {
	isTool()
}

func (*FileSearchTool) isTool()         {}
func (*FunctionTool) isTool()           {}
func (*WebSearchPreviewTool) isTool()   {}
func (*ComputerUsePreviewTool) isTool() {}

// UnmarshalTool unmarshals JSON into the correct Tool variant
// based on the "type" discriminator field.
func UnmarshalTool(data []byte) (Tool, error) {
	var disc struct {
		D string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.D {
	case "file_search":
		var val FileSearchTool
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "function":
		var val FunctionTool
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "web_search_preview":
		var val WebSearchPreviewTool
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "computer_use_preview":
		var val ComputerUsePreviewTool
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	default:
		return nil, fmt.Errorf("unknown type %q for Tool", disc.D)
	}
}
