// Package emitter generates output files from the Schema IR.
package emitter

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/codewandler/compschema/internal/ir"
)

// isAnyType returns true if the type is an interface{}/any alias
// that cannot have methods defined on it.
func isAnyType(t *ir.Type) bool {
	return t.Kind == ir.KindScalar && t.ScalarType == "any"
}

// isWrapperType returns true if the type is a primitive wrapper struct
// generated by uniongen (e.g. `type FooString struct { Value string }`).
// These types have custom MarshalJSON that serializes as the inner value,
// so their JSON form doesn't match the struct form.
func isWrapperType(t *ir.Type) bool {
	if t.Kind != ir.KindStruct || len(t.Fields) != 1 {
		return false
	}
	return t.Fields[0].JSONName == "Value" || t.Fields[0].JSONName == "value"
}

// EmitOptions controls optional features of the JSON Schema emitter.
type EmitOptions struct {
	Examples bool // add "examples" arrays to $defs
}

// JSONSchema emits a JSON Schema draft 2020-12 document from an IR Package.
// Single-use enum and scalar $defs are inlined at their reference site.
func JSONSchema(pkg *ir.Package) ([]byte, map[string]bool, error) {
	return JSONSchemaWithOptions(pkg, EmitOptions{})
}

// JSONSchemaWithOptions emits a JSON Schema with configurable options.
func JSONSchemaWithOptions(pkg *ir.Package, opts EmitOptions) ([]byte, map[string]bool, error) {
	defs := make(map[string]any)

	for _, name := range pkg.Order {
		t := pkg.Types[name]
		defs[name] = typeToSchema(t, true)
	}

	// Add examples before inlining so inlined types carry their examples.
	if opts.Examples {
		AddExamples(defs, pkg)
	}

	// Inline single-use trivial $defs.
	inlined := inlineDefs(defs, pkg)

	doc := map[string]any{
		"$schema": "https://json-schema.org/draft/2020-12/schema",
		"$defs":   defs,
	}

	data, err := json.MarshalIndent(doc, "", "  ")
	return data, inlined, err
}

// inlineDefs replaces single-use $ref to trivial types (enums, scalars)
// with their inline schema, and removes them from $defs.
func inlineDefs(defs map[string]any, pkg *ir.Package) map[string]bool {
	refCounts := make(map[string]int)
	countRefs(defs, refCounts)

	inlined := make(map[string]bool)
	for name, count := range refCounts {
		if count != 1 {
			continue
		}
		t, ok := pkg.Types[name]
		if !ok {
			continue
		}
		if t.Kind == ir.KindEnum || t.Kind == ir.KindScalar {
			inlined[name] = true
		}
	}

	for name := range inlined {
		schema := defs[name]
		replaceRef(defs, "#/$defs/"+name, schema)
		delete(defs, name)
	}

	return inlined
}

// countRefs counts how many times each $def name appears as a $ref target.
func countRefs(v any, counts map[string]int) {
	switch val := v.(type) {
	case map[string]any:
		if ref, ok := val["$ref"]; ok {
			if s, ok := ref.(string); ok && strings.HasPrefix(s, "#/$defs/") {
				name := strings.TrimPrefix(s, "#/$defs/")
				counts[name]++
			}
		}
		for _, child := range val {
			countRefs(child, counts)
		}
	case []any:
		for _, child := range val {
			countRefs(child, counts)
		}
	}
}

// replaceRef recursively replaces {"$ref": target} with the inline schema.
// If the object has additional keys alongside $ref (e.g. description), those
// are merged into the replacement.
func replaceRef(v any, target string, replacement any) {
	switch val := v.(type) {
	case map[string]any:
		for k, child := range val {
			if childMap, ok := child.(map[string]any); ok {
				if ref, ok := childMap["$ref"]; ok && ref == target {
					// Merge: start with replacement, add extra keys from the ref object.
					if replMap, ok := replacement.(map[string]any); ok {
						merged := make(map[string]any, len(replMap)+len(childMap))
						for rk, rv := range replMap {
							merged[rk] = rv
						}
						for ck, cv := range childMap {
							if ck != "$ref" {
								merged[ck] = cv
							}
						}
						val[k] = merged
					} else {
						val[k] = replacement
					}
					continue
				}
			}
			replaceRef(child, target, replacement)
		}
	case []any:
		for i, child := range val {
			if childMap, ok := child.(map[string]any); ok {
				if ref, ok := childMap["$ref"]; ok && ref == target {
					if replMap, ok := replacement.(map[string]any); ok {
						merged := make(map[string]any, len(replMap)+len(childMap))
						for rk, rv := range replMap {
							merged[rk] = rv
						}
						for ck, cv := range childMap {
							if ck != "$ref" {
								merged[ck] = cv
							}
						}
						val[i] = merged
					} else {
						val[i] = replacement
					}
					continue
				}
			}
			replaceRef(child, target, replacement)
		}
	}
}

// typeToSchema converts an IR Type into a JSON Schema map.
func typeToSchema(t *ir.Type, topLevel bool) map[string]any {
	if t == nil {
		return map[string]any{}
	}

	s := make(map[string]any)

	if t.Description != "" && topLevel {
		s["description"] = t.Description
	}

	switch t.Kind {
	case ir.KindStruct:
		s["type"] = "object"
		if topLevel && t.Name != "" {
			s["title"] = t.Name
		}
		props := make(map[string]any)
		var required []string
		for _, f := range t.Fields {
			prop := typeRefToSchema(f.Type)
			if f.Description != "" {
				prop["description"] = f.Description
			}
			for _, c := range f.Constraints {
				prop[c.Keyword] = c.Value
			}
			props[f.JSONName] = prop
			if f.Required {
				required = append(required, f.JSONName)
			}
		}
		if len(props) > 0 {
			s["properties"] = props
		}
		if len(required) > 0 {
			s["required"] = required
		}
		s["additionalProperties"] = false

	case ir.KindEnum:
		s["type"] = t.EnumType
		s["enum"] = t.EnumValues
		if topLevel && t.Name != "" {
			s["title"] = t.Name
		}

	case ir.KindUnion:
		variants := make([]any, 0, len(t.Variants))
		for _, v := range t.Variants {
			variants = append(variants, typeRefToSchema(v.TypeRef))
		}
		s["oneOf"] = variants
		if t.Discriminator != "" {
			s["discriminator"] = map[string]any{
				"propertyName": t.Discriminator,
			}
		}

	case ir.KindScalar:
		if t.ScalarType == "any" {
			// interface{} — accepts any JSON value.
			return s
		}
		s["type"] = t.ScalarType

	case ir.KindList:
		s["type"] = "array"
		if t.Items != nil {
			s["items"] = typeRefToSchema(*t.Items)
		}

	case ir.KindMap:
		s["type"] = "object"
		if t.MapValue != nil {
			s["additionalProperties"] = typeRefToSchema(*t.MapValue)
		}

	case ir.KindNullable:
		if t.Inner != nil {
			inner := typeRefToSchema(*t.Inner)
			// Merge null into type.
			if typ, ok := inner["type"]; ok {
				inner["type"] = []any{typ, "null"}
			} else if ref, ok := inner["$ref"]; ok {
				// Nullable $ref → oneOf.
				return map[string]any{
					"oneOf": []any{
						map[string]any{"$ref": ref},
						map[string]any{"type": "null"},
					},
				}
			}
			return inner
		}

	case ir.KindRef:
		s["$ref"] = "#/$defs/" + t.RefName
	}

	// Apply constraints.
	for _, c := range t.Constraints {
		s[c.Keyword] = c.Value
	}

	return s
}

// typeRefToSchema converts an IR TypeRef to a JSON Schema.
func typeRefToSchema(ref ir.TypeRef) map[string]any {
	if ref.Name != "" {
		return map[string]any{"$ref": "#/$defs/" + ref.Name}
	}
	if ref.Inline != nil {
		return typeToSchema(ref.Inline, false)
	}
	return map[string]any{}
}

// GoCodegen emits the compschema.gen.go file contents.
// inlinedTypes is the set of type names that were inlined into parent schemas
// and should not get their own methods.
func GoCodegen(pkg *ir.Package, inlinedTypes map[string]bool) string {
	var b strings.Builder

	b.WriteString("// Code generated by compschema. DO NOT EDIT.\n\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", pkg.Name))
	b.WriteString("import (\n")
	b.WriteString("\t_ \"embed\"\n")
	b.WriteString("\t\"encoding/json\"\n")
	b.WriteString("\t\"sync\"\n\n")
	b.WriteString("\t\"github.com/santhosh-tekuri/jsonschema/v6\"\n")
	b.WriteString(")\n\n")

	// Embed.
	b.WriteString("//go:embed schema.gen.json\n")
	b.WriteString("var compschemaJSON []byte\n\n")

	// Def cache.
	b.WriteString("var compschemaDefCache sync.Map\n\n")
	b.WriteString("func compschemaDefBytes(name string) json.RawMessage {\n")
	b.WriteString("\tif v, ok := compschemaDefCache.Load(name); ok {\n")
	b.WriteString("\t\treturn v.(json.RawMessage)\n")
	b.WriteString("\t}\n")
	b.WriteString("\tvar full struct {\n")
	b.WriteString("\t\tDefs map[string]json.RawMessage `json:\"$defs\"`\n")
	b.WriteString("\t}\n")
	b.WriteString("\tjson.Unmarshal(compschemaJSON, &full)\n")
	b.WriteString("\tb := full.Defs[name]\n")
	b.WriteString("\tcompschemaDefCache.Store(name, b)\n")
	b.WriteString("\treturn b\n")
	b.WriteString("}\n\n")

	// Per-type compiled validators.
	b.WriteString("var compschemaValidators sync.Map\n\n")
	b.WriteString("func compschemaValidator(name string) *jsonschema.Schema {\n")
	b.WriteString("\tif v, ok := compschemaValidators.Load(name); ok {\n")
	b.WriteString("\t\treturn v.(*jsonschema.Schema)\n")
	b.WriteString("\t}\n")
	b.WriteString("\tc := jsonschema.NewCompiler()\n")
	b.WriteString("\tvar doc any\n")
	b.WriteString("\tif err := json.Unmarshal(compschemaJSON, &doc); err != nil {\n")
	b.WriteString("\t\tpanic(\"compschema: \" + err.Error())\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif err := c.AddResource(\"schema.json\", doc); err != nil {\n")
	b.WriteString("\t\tpanic(\"compschema: \" + err.Error())\n")
	b.WriteString("\t}\n")
	b.WriteString("\tsch, err := c.Compile(\"schema.json#/$defs/\" + name)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\tpanic(\"compschema: \" + err.Error())\n")
	b.WriteString("\t}\n")
	b.WriteString("\tcompschemaValidators.Store(name, sch)\n")
	b.WriteString("\treturn sch\n")
	b.WriteString("}\n\n")

	// Per-type methods.
	for _, name := range pkg.Order {
		if inlinedTypes[name] {
			continue
		}
		t := pkg.Types[name]
		if t.Kind == ir.KindUnion || isAnyType(t) {
			// Unions and any-aliases are interfaces — use a free function, not a method.
			b.WriteString(fmt.Sprintf("// %sJSONSchemaBytes returns the JSON Schema for the %s union.\n", name, name))
			b.WriteString(fmt.Sprintf("func %sJSONSchemaBytes() json.RawMessage { return compschemaDefBytes(%q) }\n\n", name, name))
			continue
		}
		if t.Kind == ir.KindEnum || t.Kind == ir.KindScalar || t.Kind == ir.KindList || t.Kind == ir.KindMap {
			b.WriteString(fmt.Sprintf("// JSONSchemaBytes returns the JSON Schema for %s.\n", name))
			b.WriteString(fmt.Sprintf("func (%s) JSONSchemaBytes() json.RawMessage { return compschemaDefBytes(%q) }\n\n", name, name))
			continue
		}
		if t.Kind != ir.KindStruct {
			continue
		}

		// JSONSchemaBytes
		b.WriteString(fmt.Sprintf("// JSONSchemaBytes returns the JSON Schema definition for %s.\n", name))
		b.WriteString(fmt.Sprintf("func (%s) JSONSchemaBytes() json.RawMessage { return compschemaDefBytes(%q) }\n\n", name, name))

		// Validate
		b.WriteString(fmt.Sprintf("// Validate checks whether raw JSON conforms to the %s schema.\n", name))
		b.WriteString(fmt.Sprintf("func (%s) Validate(data []byte) error {\n", name))
		b.WriteString(fmt.Sprintf("\tsch := compschemaValidator(%q)\n", name))
		b.WriteString("\tvar v any\n")
		b.WriteString("\tif err := json.Unmarshal(data, &v); err != nil {\n")
		b.WriteString("\t\treturn err\n")
		b.WriteString("\t}\n")
		b.WriteString("\treturn sch.Validate(v)\n")
		b.WriteString("}\n\n")

		// Decode
		b.WriteString(fmt.Sprintf("// Decode%s validates and unmarshals JSON into a %s.\n", name, name))
		b.WriteString(fmt.Sprintf("func Decode%s(data []byte) (%s, error) {\n", name, name))
		b.WriteString(fmt.Sprintf("\tvar zero %s\n", name))
		b.WriteString("\tif err := zero.Validate(data); err != nil {\n")
		b.WriteString(fmt.Sprintf("\t\treturn %s{}, err\n", name))
		b.WriteString("\t}\n")
		b.WriteString(fmt.Sprintf("\tvar result %s\n", name))
		b.WriteString("\tif err := json.Unmarshal(data, &result); err != nil {\n")
		b.WriteString(fmt.Sprintf("\t\treturn %s{}, err\n", name))
		b.WriteString("\t}\n")
		b.WriteString("\treturn result, nil\n")
		b.WriteString("}\n\n")
	}

	return b.String()
}

// GoTests emits the compschema_test.gen.go file contents.
func GoTests(pkg *ir.Package, inlinedTypes map[string]bool) string {
	return GoTestsWithOptions(pkg, inlinedTypes, EmitOptions{})
}

// GoTestsWithOptions emits tests with configurable options.
func GoTestsWithOptions(pkg *ir.Package, inlinedTypes map[string]bool, opts EmitOptions) string {
	var b strings.Builder

	b.WriteString("// Code generated by compschema. DO NOT EDIT.\n\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", pkg.Name))
	b.WriteString("import (\n")
	b.WriteString("\t\"encoding/json\"\n")
	b.WriteString("\t\"testing\"\n")
	b.WriteString(")\n\n")

	// Package-level tests.
	b.WriteString("func TestCompschema_SchemaIsValidJSON(t *testing.T) {\n")
	b.WriteString("\tvar v any\n")
	b.WriteString("\tif err := json.Unmarshal(compschemaJSON, &v); err != nil {\n")
	b.WriteString("\t\tt.Fatalf(\"schema.gen.json is not valid JSON: %v\", err)\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")

	// Per-type tests.
	for _, name := range pkg.Order {
		if inlinedTypes[name] {
			continue
		}
		t := pkg.Types[name]

		// Skip any-typed aliases — can't instantiate or call methods on them.
		if isAnyType(t) {
			continue
		}

		// JSONSchemaBytes test — for all types.
		b.WriteString(fmt.Sprintf("func TestCompschema_%s_JSONSchemaBytes(t *testing.T) {\n", name))
		switch {
		case t.Kind == ir.KindUnion:
			b.WriteString(fmt.Sprintf("\tb := %sJSONSchemaBytes()\n", name))
		case t.Kind == ir.KindEnum || t.Kind == ir.KindScalar:
			b.WriteString(fmt.Sprintf("\tb := %s(\"\").JSONSchemaBytes()\n", name))
		default:
			b.WriteString(fmt.Sprintf("\tb := (%s{}).JSONSchemaBytes()\n", name))
		}
		b.WriteString("\tif len(b) == 0 {\n")
		b.WriteString("\t\tt.Fatal(\"JSONSchemaBytes returned empty\")\n")
		b.WriteString("\t}\n")
		b.WriteString("\tvar v any\n")
		b.WriteString("\tif err := json.Unmarshal(b, &v); err != nil {\n")
		b.WriteString("\t\tt.Fatalf(\"JSONSchemaBytes is not valid JSON: %v\", err)\n")
		b.WriteString("\t}\n")
		b.WriteString("}\n\n")

		if t.Kind != ir.KindStruct {
			continue
		}

		// Validate rejects invalid JSON.
		b.WriteString(fmt.Sprintf("func TestCompschema_%s_ValidateRejectsInvalidJSON(t *testing.T) {\n", name))
		b.WriteString(fmt.Sprintf("\terr := (%s{}).Validate([]byte(`{not json}`))\n", name))
		b.WriteString("\tif err == nil {\n")
		b.WriteString("\t\tt.Fatal(\"Validate should reject invalid JSON\")\n")
		b.WriteString("\t}\n")
		b.WriteString("}\n\n")

		// Validate rejects wrong type.
		b.WriteString(fmt.Sprintf("func TestCompschema_%s_ValidateRejectsWrongType(t *testing.T) {\n", name))
		b.WriteString(fmt.Sprintf("\terr := (%s{}).Validate([]byte(`\"a string\"`))\n", name))
		b.WriteString("\tif err == nil {\n")
		b.WriteString(fmt.Sprintf("\t\tt.Fatal(\"%s.Validate should reject a string for an object type\")\n", name))
		b.WriteString("\t}\n")
		b.WriteString("}\n\n")

		// Validate rejects empty object (if type has required fields).
		if t.HasRequired() {
			b.WriteString(fmt.Sprintf("func TestCompschema_%s_ValidateRejectsEmpty(t *testing.T) {\n", name))
			b.WriteString(fmt.Sprintf("\terr := (%s{}).Validate([]byte(`{}`))\n", name))
			b.WriteString("\tif err == nil {\n")
			b.WriteString(fmt.Sprintf("\t\tt.Fatal(\"%s.Validate({}) should fail (has required fields)\")\n", name))
			b.WriteString("\t}\n")
			b.WriteString("}\n\n")
		}

		// Round-trip test.
		b.WriteString(fmt.Sprintf("func TestCompschema_%s_RoundTrip(t *testing.T) {\n", name))
		fixture, feasible := generateFixture(t, pkg)
		if !feasible {
			b.WriteString("\tt.Skip(\"type has fields with union/interface types that cannot be auto-fixtured\")\n")
		} else if fixture == "" {
			b.WriteString("\tt.Skip(\"auto-generated fixture not available for this type\")\n")
		} else {
			b.WriteString(fmt.Sprintf("\tdata := []byte(`%s`)\n", fixture))
			b.WriteString(fmt.Sprintf("\tresult, err := Decode%s(data)\n", name))
			b.WriteString("\tif err != nil {\n")
			b.WriteString("\t\tt.Fatalf(\"Decode: %v\", err)\n")
			b.WriteString("\t}\n")
			b.WriteString("\treencoded, err := json.Marshal(result)\n")
			b.WriteString("\tif err != nil {\n")
			b.WriteString("\t\tt.Fatalf(\"re-marshal: %v\", err)\n")
			b.WriteString("\t}\n")
			b.WriteString("\t_ = reencoded // round-trip succeeded\n")
		}
		b.WriteString("}\n\n")
	}

	// Example validation tests — one table-driven test covering all types.
	if opts.Examples {
		b.WriteString("func TestCompschema_ExamplesValidate(t *testing.T) {\n")
		b.WriteString("\ttests := []struct {\n")
		b.WriteString("\t\tname    string\n")
		b.WriteString("\t\texample string\n")
		b.WriteString("\t}{\n")

		for _, name := range pkg.Order {
			if inlinedTypes[name] {
				continue
			}
			t := pkg.Types[name]
			if isAnyType(t) {
				continue
			}

			ex := GenerateExample(t, pkg)
			if ex == nil {
				continue
			}
			exJSON, err := json.Marshal(ex)
			if err != nil {
				continue
			}
			// Escape backticks in the JSON for raw string literals.
			exStr := strings.ReplaceAll(string(exJSON), "`", "`+\"`\"+`")
			b.WriteString(fmt.Sprintf("\t\t{%q, `%s`},\n", name, exStr))
		}

		b.WriteString("\t}\n")
		b.WriteString("\tfor _, tt := range tests {\n")
		b.WriteString("\t\tt.Run(tt.name, func(t *testing.T) {\n")
		b.WriteString("\t\t\t// Verify example is valid JSON.\n")
		b.WriteString("\t\t\tvar v any\n")
		b.WriteString("\t\t\tif err := json.Unmarshal([]byte(tt.example), &v); err != nil {\n")
		b.WriteString("\t\t\t\tt.Fatalf(\"example is not valid JSON: %v\", err)\n")
		b.WriteString("\t\t\t}\n")
		b.WriteString("\t\t\t// Validate against schema.\n")
		b.WriteString("\t\t\tsch := compschemaValidator(tt.name)\n")
		b.WriteString("\t\t\tif err := sch.Validate(v); err != nil {\n")
		b.WriteString("\t\t\t\tt.Errorf(\"example failed validation: %v\", err)\n")
		b.WriteString("\t\t\t}\n")
		b.WriteString("\t\t})\n")
		b.WriteString("\t}\n")
		b.WriteString("}\n\n")
	}

	return b.String()
}

// generateFixture creates a minimal valid JSON string for a struct type.
// Returns the JSON string and whether the fixture is feasible (no interface{} fields).
func generateFixture(t *ir.Type, pkg *ir.Package) (string, bool) {
	if t.Kind != ir.KindStruct {
		return "", false
	}

	// Wrapper types (single "Value" field with MarshalJSON) serialize as their
	// inner value, not as a JSON object — skip round-trip auto-fixture.
	if isWrapperType(t) {
		return "", false
	}

	visiting := make(map[string]bool)
	feasible := true
	fields := make(map[string]any)
	for _, f := range t.Fields {
		if !f.Required {
			continue
		}
		val, ok := fieldZeroValue(f, pkg, visiting)
		if !ok {
			feasible = false
		}
		fields[f.JSONName] = val
	}

	b, err := json.Marshal(fields)
	if err != nil {
		return "", false
	}
	return string(b), feasible
}

// fieldZeroValue produces a minimal valid value for a field.
func fieldZeroValue(f ir.Field, pkg *ir.Package, visiting map[string]bool) (any, bool) {
	// Check for const constraint.
	for _, c := range f.Constraints {
		if c.Keyword == "const" {
			return c.Value, true
		}
	}

	val, feasible := typeRefZeroValue(f.Type, pkg, visiting)

	// Apply constraints to adjust the zero value.
	for _, c := range f.Constraints {
		switch c.Keyword {
		case "minimum":
			if min, ok := toFloat(c.Value); ok {
				if cur, ok := toFloat(val); ok && cur < min {
					if min == float64(int64(min)) {
						val = int64(min)
					} else {
						val = min
					}
				}
			}
		case "minLength":
			if ml, ok := toFloat(c.Value); ok && ml > 0 {
				if s, ok := val.(string); ok && len(s) < int(ml) {
					val = strings.Repeat("x", int(ml))
				}
			}
		case "pattern":
			if _, ok := val.(string); ok {
				p := fmt.Sprintf("%v", c.Value)
				if strings.Contains(p, "[A-Z]") && strings.Contains(p, "[0-9]") {
					val = "AAA-000"
				} else {
					val = "test"
				}
			}
		case "minItems":
			if mi, ok := toFloat(c.Value); ok && mi > 0 {
				if arr, ok := val.([]any); ok && len(arr) < int(mi) {
					for len(arr) < int(mi) {
						if len(arr) > 0 {
							arr = append(arr, arr[0])
						} else {
							arr = append(arr, nil)
						}
					}
					val = arr
				}
			}
		}
	}

	return val, feasible
}

func toFloat(v any) (float64, bool) {
	switch n := v.(type) {
	case int:
		return float64(n), true
	case int64:
		return float64(n), true
	case float64:
		return n, true
	case json.Number:
		f, err := n.Float64()
		return f, err == nil
	}
	return 0, false
}

func typeRefZeroValue(ref ir.TypeRef, pkg *ir.Package, visiting map[string]bool) (any, bool) {
	if ref.Name != "" {
		if visiting[ref.Name] {
			return nil, false // cycle detected
		}
		visiting[ref.Name] = true
		defer func() { delete(visiting, ref.Name) }()

		if t, ok := pkg.Types[ref.Name]; ok {
			switch t.Kind {
			case ir.KindEnum:
				if len(t.EnumValues) > 0 {
					return t.EnumValues[0], true
				}
				return "", true
			case ir.KindStruct:
				fields := make(map[string]any)
				feasible := true
				for _, f := range t.Fields {
					if f.Required {
						v, ok := fieldZeroValue(f, pkg, visiting)
						if !ok {
							feasible = false
						}
						fields[f.JSONName] = v
					}
				}
				return fields, feasible
			case ir.KindUnion:
				// Can't auto-generate a valid union variant.
				return "", false
			case ir.KindScalar:
				if t.ScalarType == "any" {
					return nil, false
				}
				return scalarZero(t.ScalarType), true
			case ir.KindMap:
				return map[string]any{}, true
			case ir.KindList:
				return []any{}, true
			}
		}
		return nil, false // type not in IR, can't generate fixture
	}

	if ref.Inline == nil {
		return "", true
	}

	switch ref.Inline.Kind {
	case ir.KindScalar:
		if ref.Inline.ScalarType == "any" {
			return nil, false // interface{} — can't generate valid fixture
		}
		return scalarZero(ref.Inline.ScalarType), true
	case ir.KindList:
		if ref.Inline.Items != nil {
			item, ok := typeRefZeroValue(*ref.Inline.Items, pkg, visiting)
			return []any{item}, ok
		}
		return []any{}, true
	case ir.KindNullable:
		if ref.Inline.Inner != nil {
			return typeRefZeroValue(*ref.Inline.Inner, pkg, visiting)
		}
		return nil, true
	case ir.KindMap:
		return map[string]any{}, true
	default:
		return "", true
	}
}

func scalarZero(t string) any {
	switch t {
	case "string":
		return ""
	case "integer":
		return 0
	case "number":
		return 0.0
	case "boolean":
		return false
	default:
		return ""
	}
}
