// Package emitter generates output files from the Schema IR.
package emitter

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/codewandler/compschema/internal/ir"
)

// JSONSchema emits a JSON Schema draft 2020-12 document from an IR Package.
// All types are placed in $defs; the document has no root $ref.
func JSONSchema(pkg *ir.Package) ([]byte, error) {
	defs := make(map[string]any)

	for _, name := range pkg.Order {
		t := pkg.Types[name]
		defs[name] = typeToSchema(t, true)
	}

	doc := map[string]any{
		"$schema": "https://json-schema.org/draft/2020-12/schema",
		"$defs":   defs,
	}

	return json.MarshalIndent(doc, "", "  ")
}

// typeToSchema converts an IR Type into a JSON Schema map.
func typeToSchema(t *ir.Type, topLevel bool) map[string]any {
	if t == nil {
		return map[string]any{}
	}

	s := make(map[string]any)

	if t.Description != "" && topLevel {
		s["description"] = t.Description
	}

	switch t.Kind {
	case ir.KindStruct:
		s["type"] = "object"
		if topLevel && t.Name != "" {
			s["title"] = t.Name
		}
		props := make(map[string]any)
		var required []string
		for _, f := range t.Fields {
			prop := typeRefToSchema(f.Type)
			if f.Description != "" {
				prop["description"] = f.Description
			}
			for _, c := range f.Constraints {
				prop[c.Keyword] = c.Value
			}
			props[f.JSONName] = prop
			if f.Required {
				required = append(required, f.JSONName)
			}
		}
		if len(props) > 0 {
			s["properties"] = props
		}
		if len(required) > 0 {
			s["required"] = required
		}
		s["additionalProperties"] = false

	case ir.KindEnum:
		s["type"] = t.EnumType
		s["enum"] = t.EnumValues
		if topLevel && t.Name != "" {
			s["title"] = t.Name
		}

	case ir.KindUnion:
		variants := make([]any, 0, len(t.Variants))
		for _, v := range t.Variants {
			variants = append(variants, typeRefToSchema(v.TypeRef))
		}
		s["oneOf"] = variants
		if t.Discriminator != "" {
			s["discriminator"] = map[string]any{
				"propertyName": t.Discriminator,
			}
		}

	case ir.KindScalar:
		if t.ScalarType == "any" {
			// interface{} — accepts any JSON value.
			return s
		}
		s["type"] = t.ScalarType

	case ir.KindList:
		s["type"] = "array"
		if t.Items != nil {
			s["items"] = typeRefToSchema(*t.Items)
		}

	case ir.KindMap:
		s["type"] = "object"
		if t.MapValue != nil {
			s["additionalProperties"] = typeRefToSchema(*t.MapValue)
		}

	case ir.KindNullable:
		if t.Inner != nil {
			inner := typeRefToSchema(*t.Inner)
			// Merge null into type.
			if typ, ok := inner["type"]; ok {
				inner["type"] = []any{typ, "null"}
			} else if ref, ok := inner["$ref"]; ok {
				// Nullable $ref → oneOf.
				return map[string]any{
					"oneOf": []any{
						map[string]any{"$ref": ref},
						map[string]any{"type": "null"},
					},
				}
			}
			return inner
		}

	case ir.KindRef:
		s["$ref"] = "#/$defs/" + t.RefName
	}

	// Apply constraints.
	for _, c := range t.Constraints {
		s[c.Keyword] = c.Value
	}

	return s
}

// typeRefToSchema converts an IR TypeRef to a JSON Schema.
func typeRefToSchema(ref ir.TypeRef) map[string]any {
	if ref.Name != "" {
		return map[string]any{"$ref": "#/$defs/" + ref.Name}
	}
	if ref.Inline != nil {
		return typeToSchema(ref.Inline, false)
	}
	return map[string]any{}
}

// GoCodegen emits the compschema.gen.go file contents.
func GoCodegen(pkg *ir.Package) string {
	var b strings.Builder

	b.WriteString("// Code generated by compschema. DO NOT EDIT.\n\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", pkg.Name))
	b.WriteString("import (\n")
	b.WriteString("\t_ \"embed\"\n")
	b.WriteString("\t\"encoding/json\"\n")
	b.WriteString("\t\"sync\"\n\n")
	b.WriteString("\t\"github.com/santhosh-tekuri/jsonschema/v6\"\n")
	b.WriteString(")\n\n")

	// Embed.
	b.WriteString("//go:embed schema.gen.json\n")
	b.WriteString("var compschemaJSON []byte\n\n")

	// Def cache.
	b.WriteString("var compschemaDefCache sync.Map\n\n")
	b.WriteString("func compschemaDefBytes(name string) []byte {\n")
	b.WriteString("\tif v, ok := compschemaDefCache.Load(name); ok {\n")
	b.WriteString("\t\treturn v.([]byte)\n")
	b.WriteString("\t}\n")
	b.WriteString("\tvar full struct {\n")
	b.WriteString("\t\tDefs map[string]json.RawMessage `json:\"$defs\"`\n")
	b.WriteString("\t}\n")
	b.WriteString("\tjson.Unmarshal(compschemaJSON, &full)\n")
	b.WriteString("\tb := full.Defs[name]\n")
	b.WriteString("\tcompschemaDefCache.Store(name, []byte(b))\n")
	b.WriteString("\treturn b\n")
	b.WriteString("}\n\n")

	// Per-type compiled validators.
	b.WriteString("var compschemaValidators sync.Map\n\n")
	b.WriteString("func compschemaValidator(name string) *jsonschema.Schema {\n")
	b.WriteString("\tif v, ok := compschemaValidators.Load(name); ok {\n")
	b.WriteString("\t\treturn v.(*jsonschema.Schema)\n")
	b.WriteString("\t}\n")
	b.WriteString("\tc := jsonschema.NewCompiler()\n")
	b.WriteString("\tvar doc any\n")
	b.WriteString("\tif err := json.Unmarshal(compschemaJSON, &doc); err != nil {\n")
	b.WriteString("\t\tpanic(\"compschema: \" + err.Error())\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif err := c.AddResource(\"schema.json\", doc); err != nil {\n")
	b.WriteString("\t\tpanic(\"compschema: \" + err.Error())\n")
	b.WriteString("\t}\n")
	b.WriteString("\tsch, err := c.Compile(\"schema.json#/$defs/\" + name)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\tpanic(\"compschema: \" + err.Error())\n")
	b.WriteString("\t}\n")
	b.WriteString("\tcompschemaValidators.Store(name, sch)\n")
	b.WriteString("\treturn sch\n")
	b.WriteString("}\n\n")

	// Per-type methods.
	for _, name := range pkg.Order {
		t := pkg.Types[name]
		if t.Kind == ir.KindUnion {
			// Unions are interfaces — use a free function, not a method.
			b.WriteString(fmt.Sprintf("// %sJSONSchemaBytes returns the JSON Schema for the %s union.\n", name, name))
			b.WriteString(fmt.Sprintf("func %sJSONSchemaBytes() []byte { return compschemaDefBytes(%q) }\n\n", name, name))
			continue
		}
		if t.Kind == ir.KindEnum || t.Kind == ir.KindScalar || t.Kind == ir.KindList || t.Kind == ir.KindMap {
			b.WriteString(fmt.Sprintf("// JSONSchemaBytes returns the JSON Schema for %s.\n", name))
			b.WriteString(fmt.Sprintf("func (%s) JSONSchemaBytes() []byte { return compschemaDefBytes(%q) }\n\n", name, name))
			continue
		}
		if t.Kind != ir.KindStruct {
			continue
		}

		// JSONSchemaBytes
		b.WriteString(fmt.Sprintf("// JSONSchemaBytes returns the JSON Schema definition for %s.\n", name))
		b.WriteString(fmt.Sprintf("func (%s) JSONSchemaBytes() []byte { return compschemaDefBytes(%q) }\n\n", name, name))

		// Validate
		b.WriteString(fmt.Sprintf("// Validate checks whether raw JSON conforms to the %s schema.\n", name))
		b.WriteString(fmt.Sprintf("func (%s) Validate(data []byte) error {\n", name))
		b.WriteString(fmt.Sprintf("\tsch := compschemaValidator(%q)\n", name))
		b.WriteString("\tvar v any\n")
		b.WriteString("\tif err := json.Unmarshal(data, &v); err != nil {\n")
		b.WriteString("\t\treturn err\n")
		b.WriteString("\t}\n")
		b.WriteString("\treturn sch.Validate(v)\n")
		b.WriteString("}\n\n")

		// Decode
		b.WriteString(fmt.Sprintf("// Decode%s validates and unmarshals JSON into a %s.\n", name, name))
		b.WriteString(fmt.Sprintf("func Decode%s(data []byte) (%s, error) {\n", name, name))
		b.WriteString(fmt.Sprintf("\tvar zero %s\n", name))
		b.WriteString("\tif err := zero.Validate(data); err != nil {\n")
		b.WriteString(fmt.Sprintf("\t\treturn %s{}, err\n", name))
		b.WriteString("\t}\n")
		b.WriteString(fmt.Sprintf("\tvar result %s\n", name))
		b.WriteString("\tif err := json.Unmarshal(data, &result); err != nil {\n")
		b.WriteString(fmt.Sprintf("\t\treturn %s{}, err\n", name))
		b.WriteString("\t}\n")
		b.WriteString("\treturn result, nil\n")
		b.WriteString("}\n\n")
	}

	return b.String()
}

// GoTests emits the compschema_test.gen.go file contents.
func GoTests(pkg *ir.Package) string {
	var b strings.Builder

	b.WriteString("// Code generated by compschema. DO NOT EDIT.\n\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", pkg.Name))
	b.WriteString("import (\n")
	b.WriteString("\t\"encoding/json\"\n")
	b.WriteString("\t\"testing\"\n")
	b.WriteString(")\n\n")

	// Package-level tests.
	b.WriteString("func TestCompschema_SchemaIsValidJSON(t *testing.T) {\n")
	b.WriteString("\tvar v any\n")
	b.WriteString("\tif err := json.Unmarshal(compschemaJSON, &v); err != nil {\n")
	b.WriteString("\t\tt.Fatalf(\"schema.gen.json is not valid JSON: %v\", err)\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")

	// Per-type tests.
	for _, name := range pkg.Order {
		t := pkg.Types[name]

		// JSONSchemaBytes test — for all types.
		b.WriteString(fmt.Sprintf("func TestCompschema_%s_JSONSchemaBytes(t *testing.T) {\n", name))
		switch t.Kind {
		case ir.KindUnion:
			b.WriteString(fmt.Sprintf("\tb := %sJSONSchemaBytes()\n", name))
		case ir.KindEnum, ir.KindScalar:
			b.WriteString(fmt.Sprintf("\tb := %s(\"\").JSONSchemaBytes()\n", name))
		default:
			b.WriteString(fmt.Sprintf("\tb := (%s{}).JSONSchemaBytes()\n", name))
		}
		b.WriteString("\tif len(b) == 0 {\n")
		b.WriteString("\t\tt.Fatal(\"JSONSchemaBytes returned empty\")\n")
		b.WriteString("\t}\n")
		b.WriteString("\tvar v any\n")
		b.WriteString("\tif err := json.Unmarshal(b, &v); err != nil {\n")
		b.WriteString("\t\tt.Fatalf(\"JSONSchemaBytes is not valid JSON: %v\", err)\n")
		b.WriteString("\t}\n")
		b.WriteString("}\n\n")

		if t.Kind != ir.KindStruct {
			continue
		}

		// Validate rejects invalid JSON.
		b.WriteString(fmt.Sprintf("func TestCompschema_%s_ValidateRejectsInvalidJSON(t *testing.T) {\n", name))
		b.WriteString(fmt.Sprintf("\terr := (%s{}).Validate([]byte(`{not json}`))\n", name))
		b.WriteString("\tif err == nil {\n")
		b.WriteString("\t\tt.Fatal(\"Validate should reject invalid JSON\")\n")
		b.WriteString("\t}\n")
		b.WriteString("}\n\n")

		// Validate rejects wrong type.
		b.WriteString(fmt.Sprintf("func TestCompschema_%s_ValidateRejectsWrongType(t *testing.T) {\n", name))
		b.WriteString(fmt.Sprintf("\terr := (%s{}).Validate([]byte(`\"a string\"`))\n", name))
		b.WriteString("\tif err == nil {\n")
		b.WriteString(fmt.Sprintf("\t\tt.Fatal(\"%s.Validate should reject a string for an object type\")\n", name))
		b.WriteString("\t}\n")
		b.WriteString("}\n\n")

		// Validate rejects empty object (if type has required fields).
		if t.HasRequired() {
			b.WriteString(fmt.Sprintf("func TestCompschema_%s_ValidateRejectsEmpty(t *testing.T) {\n", name))
			b.WriteString(fmt.Sprintf("\terr := (%s{}).Validate([]byte(`{}`))\n", name))
			b.WriteString("\tif err == nil {\n")
			b.WriteString(fmt.Sprintf("\t\tt.Fatal(\"%s.Validate({}) should fail (has required fields)\")\n", name))
			b.WriteString("\t}\n")
			b.WriteString("}\n\n")
		}

		// Round-trip test.
		b.WriteString(fmt.Sprintf("func TestCompschema_%s_RoundTrip(t *testing.T) {\n", name))
		fixture, feasible := generateFixture(t, pkg)
		if !feasible {
			b.WriteString("\tt.Skip(\"type has fields with union/interface types that cannot be auto-fixtured\")\n")
		} else if fixture == "" {
			b.WriteString("\tt.Skip(\"auto-generated fixture not available for this type\")\n")
		} else {
			b.WriteString(fmt.Sprintf("\tdata := []byte(`%s`)\n", fixture))
			b.WriteString(fmt.Sprintf("\tresult, err := Decode%s(data)\n", name))
			b.WriteString("\tif err != nil {\n")
			b.WriteString("\t\tt.Fatalf(\"Decode: %v\", err)\n")
			b.WriteString("\t}\n")
			b.WriteString("\treencoded, err := json.Marshal(result)\n")
			b.WriteString("\tif err != nil {\n")
			b.WriteString("\t\tt.Fatalf(\"re-marshal: %v\", err)\n")
			b.WriteString("\t}\n")
			b.WriteString("\t_ = reencoded // round-trip succeeded\n")
		}
		b.WriteString("}\n\n")
	}

	return b.String()
}

// generateFixture creates a minimal valid JSON string for a struct type.
// Returns the JSON string and whether the fixture is feasible (no interface{} fields).
func generateFixture(t *ir.Type, pkg *ir.Package) (string, bool) {
	if t.Kind != ir.KindStruct {
		return "", false
	}

	feasible := true
	fields := make(map[string]any)
	for _, f := range t.Fields {
		if !f.Required {
			continue
		}
		val, ok := fieldZeroValue(f, pkg)
		if !ok {
			feasible = false
		}
		fields[f.JSONName] = val
	}

	b, err := json.Marshal(fields)
	if err != nil {
		return "", false
	}
	return string(b), feasible
}

// fieldZeroValue produces a minimal valid value for a field.
func fieldZeroValue(f ir.Field, pkg *ir.Package) (any, bool) {
	// Check for const constraint.
	for _, c := range f.Constraints {
		if c.Keyword == "const" {
			return c.Value, true
		}
	}

	val, feasible := typeRefZeroValue(f.Type, pkg)

	// Apply constraints to adjust the zero value.
	for _, c := range f.Constraints {
		switch c.Keyword {
		case "minimum":
			if min, ok := toFloat(c.Value); ok {
				if cur, ok := toFloat(val); ok && cur < min {
					if min == float64(int64(min)) {
						val = int64(min)
					} else {
						val = min
					}
				}
			}
		case "minLength":
			if ml, ok := toFloat(c.Value); ok && ml > 0 {
				if s, ok := val.(string); ok && len(s) < int(ml) {
					val = strings.Repeat("x", int(ml))
				}
			}
		case "pattern":
			if _, ok := val.(string); ok {
				p := fmt.Sprintf("%v", c.Value)
				if strings.Contains(p, "[A-Z]") && strings.Contains(p, "[0-9]") {
					val = "AAA-000"
				} else {
					val = "test"
				}
			}
		case "minItems":
			if mi, ok := toFloat(c.Value); ok && mi > 0 {
				if arr, ok := val.([]any); ok && len(arr) < int(mi) {
					for len(arr) < int(mi) {
						if len(arr) > 0 {
							arr = append(arr, arr[0])
						} else {
							arr = append(arr, nil)
						}
					}
					val = arr
				}
			}
		}
	}

	return val, feasible
}

func toFloat(v any) (float64, bool) {
	switch n := v.(type) {
	case int:
		return float64(n), true
	case int64:
		return float64(n), true
	case float64:
		return n, true
	case json.Number:
		f, err := n.Float64()
		return f, err == nil
	}
	return 0, false
}

func typeRefZeroValue(ref ir.TypeRef, pkg *ir.Package) (any, bool) {
	if ref.Name != "" {
		if t, ok := pkg.Types[ref.Name]; ok {
			switch t.Kind {
			case ir.KindEnum:
				if len(t.EnumValues) > 0 {
					return t.EnumValues[0], true
				}
				return "", true
			case ir.KindStruct:
				fields := make(map[string]any)
				feasible := true
				for _, f := range t.Fields {
					if f.Required {
						v, ok := fieldZeroValue(f, pkg)
						if !ok {
							feasible = false
						}
						fields[f.JSONName] = v
					}
				}
				return fields, feasible
			case ir.KindUnion:
				// Can't auto-generate a valid union variant.
				return "", false
			case ir.KindScalar:
				if t.ScalarType == "any" {
					return nil, false
				}
				return scalarZero(t.ScalarType), true
			case ir.KindMap:
				return map[string]any{}, true
			case ir.KindList:
				return []any{}, true
			}
		}
		return "", true
	}

	if ref.Inline == nil {
		return "", true
	}

	switch ref.Inline.Kind {
	case ir.KindScalar:
		if ref.Inline.ScalarType == "any" {
			return nil, false // interface{} — can't generate valid fixture
		}
		return scalarZero(ref.Inline.ScalarType), true
	case ir.KindList:
		if ref.Inline.Items != nil {
			item, ok := typeRefZeroValue(*ref.Inline.Items, pkg)
			return []any{item}, ok
		}
		return []any{}, true
	case ir.KindNullable:
		if ref.Inline.Inner != nil {
			return typeRefZeroValue(*ref.Inline.Inner, pkg)
		}
		return nil, true
	default:
		return "", true
	}
}

func scalarZero(t string) any {
	switch t {
	case "string":
		return ""
	case "integer":
		return 0
	case "number":
		return 0.0
	case "boolean":
		return false
	default:
		return ""
	}
}
