// Package importer generates Go structs from JSON Schema, preserving
// constraints in jsonschema:"..." tags and generating sealed interfaces
// for oneOf/anyOf unions.
//
// This replaces go-jsonschema in the compschema pipeline with a generator
// that produces Go types that round-trip perfectly through compschema generate.
package importer

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
	"unicode"

	"github.com/codewandler/compschema/internal/ir"
	"github.com/codewandler/compschema/internal/jsonschema2ir"
	"github.com/codewandler/compschema/internal/uniongen"
)

// Import reads a JSON Schema file and generates Go source code.
func Import(schemaPath, pkg string) (string, error) {
	return ImportWithConfig(schemaPath, Config{Package: pkg})
}

// ImportWithConfig reads a JSON Schema file and generates Go source code
// with the given configuration (renames, excludes, etc.).
func ImportWithConfig(schemaPath string, cfg Config) (string, error) {
	irPkg, err := jsonschema2ir.Parse(schemaPath)
	if err != nil {
		return "", fmt.Errorf("parse schema: %w", err)
	}
	ApplyConfig(irPkg, cfg)
	return GenerateGoWithConfig(irPkg, cfg), nil
}

// ImportBytes reads JSON Schema bytes and generates Go source code.
func ImportBytes(data []byte, pkg string) (string, error) {
	irPkg, err := jsonschema2ir.ParseBytes(data)
	if err != nil {
		return "", fmt.Errorf("parse schema: %w", err)
	}
	irPkg.Name = pkg

	return GenerateGo(irPkg), nil
}

// GenerateGo produces Go source code from an IR package.
func GenerateGo(pkg *ir.Package) string {
	return GenerateGoWithConfig(pkg, Config{})
}

// GenerateGoWithConfig produces Go source code from an IR package with config.
func GenerateGoWithConfig(pkg *ir.Package, cfg Config) string {
	// Post-process: extract inline enums/unions/objects into named types.
	extractInlineEnums(pkg)

	var b strings.Builder

	b.WriteString("// Code generated by compschema import. DO NOT EDIT.\n\n")
	b.WriteString(fmt.Sprintf("package %s\n", pkg.Name))

	names := make([]string, 0, len(pkg.Types))
	names = append(names, pkg.Order...)
	sort.Strings(names)

	emitted := make(map[string]bool)
	constNames := make(map[string]bool)

	// Check if we need json/fmt imports (unions or structs with interface fields).
	needsJSON := false
	resolver := &importerResolver{pkg: pkg}
	for _, name := range names {
		t := pkg.Types[name]
		if t == nil {
			continue
		}
		if t.Kind == ir.KindUnion {
			needsJSON = true
			break
		}
		if t.Kind == ir.KindStruct {
			for _, f := range t.Fields {
				if uniongen.DetectUnionField(f, pkg, resolver, nil) != nil {
					needsJSON = true
					break
				}
			}
			if needsJSON {
				break
			}
		}
	}
	if needsJSON {
		b.WriteString("\nimport (\n\t\"encoding/json\"\n\t\"fmt\"\n)\n")
	}

	// First pass: collect all const names from enums.
	for _, name := range names {
		t := pkg.Types[name]
		if t.Kind == ir.KindEnum {
			goName := toGoName(name)
			for _, v := range t.EnumValues {
				constNames[goName+toGoName(fmt.Sprintf("%v", v))] = true
			}
		}
	}

	// Second pass: remove types that collide with enum const names.
	for _, name := range names {
		goName := toGoName(name)
		if constNames[goName] {
			delete(pkg.Types, name)
		}
	}

	// Track types emitted as unions (interfaces) — can't add methods to these.
	unionTypes := make(map[string]bool)

	// Third pass: emit types.
	for _, name := range names {
		if _, ok := pkg.Types[name]; !ok {
			continue // was deleted
		}
		goName := toGoName(name)
		if emitted[goName] {
			continue
		}
		emitted[goName] = true
		t := pkg.Types[name]
		if t.Kind == ir.KindUnion {
			unionTypes[goName] = true
		}
		b.WriteString("\n")
		emitType(&b, name, t, pkg, cfg)
	}

	// Fourth pass: emit UnmarshalJSON for structs with interface fields.
	if needsJSON {
		for _, name := range names {
			t, ok := pkg.Types[name]
			if !ok || t.Kind != ir.KindStruct {
				continue
			}
			goName := toGoName(name)
			if unionTypes[goName] {
				continue // emitted as interface, can't add methods
			}
			uniongen.EmitStructUnmarshalJSON(&b, goName, t, pkg, resolver, unionTypes)
		}
	}

	return b.String()
}

func emitType(b *strings.Builder, name string, t *ir.Type, pkg *ir.Package, cfg Config) {
	goName := toGoName(name)

	switch t.Kind {
	case ir.KindStruct:
		emitStruct(b, goName, t, pkg, cfg.Tags)

	case ir.KindEnum:
		emitEnum(b, goName, t)

	case ir.KindUnion:
		accessors := resolveAccessors(goName, name, t, cfg.Implement)
		uniongen.EmitUnion(b, goName, t, pkg, &importerResolver{pkg: pkg}, accessors...)

	case ir.KindScalar:
		if t.Description != "" {
			b.WriteString(fmt.Sprintf("// %s %s\n", goName, cleanComment(t.Description)))
		}
		b.WriteString(fmt.Sprintf("type %s %s\n", goName, scalarGoType(t.ScalarType)))

	case ir.KindList:
		elemType := "any"
		if t.Items != nil {
			elemType = typeRefGoType(t.Items, pkg)
		}
		if t.Description != "" {
			b.WriteString(fmt.Sprintf("// %s %s\n", goName, cleanComment(t.Description)))
		}
		b.WriteString(fmt.Sprintf("type %s []%s\n", goName, elemType))

	case ir.KindMap:
		valType := "any"
		if t.MapValue != nil {
			valType = typeRefGoType(t.MapValue, pkg)
		}
		if t.Description != "" {
			b.WriteString(fmt.Sprintf("// %s %s\n", goName, cleanComment(t.Description)))
		}
		b.WriteString(fmt.Sprintf("type %s map[string]%s\n", goName, valType))

	case ir.KindNullable:
		if t.Inner != nil {
			innerType := typeRefGoType(t.Inner, pkg)
			b.WriteString(fmt.Sprintf("type %s = *%s\n", goName, innerType))
		}
	}
}

func emitStruct(b *strings.Builder, goName string, t *ir.Type, pkg *ir.Package, extraTags []string) {
	if t.Description != "" {
		b.WriteString(fmt.Sprintf("// %s %s\n", goName, cleanComment(t.Description)))
	}
	b.WriteString(fmt.Sprintf("type %s struct {\n", goName))

	for _, f := range t.Fields {
		fieldGoName := toGoName(f.JSONName)
		fieldType := typeRefGoType(&f.Type, pkg)

		// Add nullable wrapper for non-required fields that aren't already pointers.
		// Skip interface types (unions) — they're already reference types.
		isUnion := false
		if f.Type.Name != "" {
			if ut, ok := pkg.Types[f.Type.Name]; ok && ut.Kind == ir.KindUnion {
				isUnion = true
			}
		}
		// Also check for nullable-wrapped union refs.
		if !isUnion && f.Type.Inline != nil && f.Type.Inline.Kind == ir.KindNullable && f.Type.Inline.Inner != nil {
			if f.Type.Inline.Inner.Name != "" {
				if ut, ok := pkg.Types[f.Type.Inline.Inner.Name]; ok && ut.Kind == ir.KindUnion {
					isUnion = true
					// Rewrite field type to use the union directly (not *interface).
					fieldType = typeRefGoType(&ir.TypeRef{Name: f.Type.Inline.Inner.Name}, pkg)
				}
			}
		}
		if !f.Required && !isUnion && !strings.HasPrefix(fieldType, "*") && !strings.HasPrefix(fieldType, "[]") && !strings.HasPrefix(fieldType, "map[") {
			fieldType = "*" + fieldType
		}

		// Build tags.
		jsonTag := f.JSONName
		if !f.Required {
			jsonTag += ",omitempty"
		}

		tags := fmt.Sprintf("`json:%q", jsonTag)

		// Extra tags (yaml, etc.) use the same name/omitempty as json.
		for _, tagName := range extraTags {
			tags += fmt.Sprintf(" %s:%q", tagName, jsonTag)
		}

		// Build jsonschema tag from constraints + description.
		jsTagParts := buildJSONSchemaTag(f.Constraints, f.Description)
		if jsTagParts != "" {
			tags += fmt.Sprintf(" jsonschema:%q", jsTagParts)
		}
		tags += "`"

		// Field comment.
		if f.Description != "" {
			b.WriteString(fmt.Sprintf("\t// %s\n", cleanComment(f.Description)))
		}
		b.WriteString(fmt.Sprintf("\t%s %s %s\n", fieldGoName, fieldType, tags))
	}

	b.WriteString("}\n")
}

func emitEnum(b *strings.Builder, goName string, t *ir.Type) {
	if t.Description != "" {
		b.WriteString(fmt.Sprintf("// %s %s\n", goName, cleanComment(t.Description)))
	}
	b.WriteString(fmt.Sprintf("type %s %s\n\n", goName, scalarGoType(t.EnumType)))

	b.WriteString("const (\n")
	seen := make(map[string]bool)
	for _, v := range t.EnumValues {
		raw := fmt.Sprintf("%v", v)
		constName := goName + toGoName(raw)
		if seen[constName] {
			continue
		}
		seen[constName] = true
		if t.EnumType == "integer" || t.EnumType == "number" {
			b.WriteString(fmt.Sprintf("\t%s %s = %s\n", constName, goName, raw))
		} else {
			b.WriteString(fmt.Sprintf("\t%s %s = %q\n", constName, goName, raw))
		}
	}
	b.WriteString(")\n")
}

// importerResolver adapts importer's helpers to the uniongen.TypeResolver interface.
type importerResolver struct {
	pkg *ir.Package
}

func (r *importerResolver) GoName(name string) string     { return toGoName(name) }
func (r *importerResolver) GoType(ref *ir.TypeRef) string { return typeRefGoType(ref, r.pkg) }
func (r *importerResolver) Comment(desc string) string    { return cleanComment(desc) }
func (r *importerResolver) IsStruct(name string) bool {
	if t, ok := r.pkg.Types[name]; ok {
		return t.Kind == ir.KindStruct
	}
	return false
}

func buildJSONSchemaTag(constraints []ir.Constraint, description string) string {
	var parts []string

	for _, c := range constraints {
		switch c.Keyword {
		case "title", "format", "default":
			parts = append(parts, fmt.Sprintf("%s=%v", c.Keyword, sanitizeTagValue(fmt.Sprintf("%v", c.Value))))
		case "minimum", "maximum", "exclusiveMinimum", "exclusiveMaximum", "multipleOf":
			parts = append(parts, fmt.Sprintf("%s=%v", c.Keyword, c.Value))
		case "minLength", "maxLength", "pattern":
			parts = append(parts, fmt.Sprintf("%s=%v", c.Keyword, c.Value))
		case "minItems", "maxItems":
			parts = append(parts, fmt.Sprintf("%s=%v", c.Keyword, c.Value))
		case "minProperties", "maxProperties":
			parts = append(parts, fmt.Sprintf("%s=%v", c.Keyword, c.Value))
		case "const":
			parts = append(parts, fmt.Sprintf("const=%v", sanitizeTagValue(fmt.Sprintf("%v", c.Value))))
		case "uniqueItems", "readOnly", "writeOnly", "deprecated":
			if v, ok := c.Value.(bool); ok && v {
				parts = append(parts, c.Keyword)
			}
		case "examples":
			// Skip — examples are schema-level, not struct tag material.
		case "description":
			// Handled separately below.
		default:
			// Preserve unknown/custom keywords.
			parts = append(parts, fmt.Sprintf("%s=%v", c.Keyword, c.Value))
		}
	}

	if description != "" {
		desc := sanitizeTagValue(description)
		parts = append(parts, "description="+desc)
	}

	return strings.Join(parts, ",")
}

// sanitizeTagValue removes backticks and normalizes whitespace for struct tags.
func sanitizeTagValue(s string) string {
	s = strings.ReplaceAll(s, "`", "'")
	s = strings.ReplaceAll(s, "\n", " ")
	s = strings.Join(strings.Fields(s), " ")
	return s
}

func typeRefGoType(ref *ir.TypeRef, pkg *ir.Package) string {
	if ref.Name != "" {
		// Check if the type was skipped (const collision) — use any.
		if _, ok := pkg.Types[ref.Name]; !ok {
			return "any"
		}
		return toGoName(ref.Name)
	}
	if ref.Inline == nil {
		return "any"
	}
	t := ref.Inline
	switch t.Kind {
	case ir.KindScalar:
		return scalarGoType(t.ScalarType)
	case ir.KindList:
		elem := "any"
		if t.Items != nil {
			elem = typeRefGoType(t.Items, pkg)
		}
		return "[]" + elem
	case ir.KindMap:
		val := "any"
		if t.MapValue != nil {
			val = typeRefGoType(t.MapValue, pkg)
		}
		return "map[string]" + val
	case ir.KindNullable:
		if t.Inner != nil {
			inner := typeRefGoType(t.Inner, pkg)
			if strings.HasPrefix(inner, "*") || strings.HasPrefix(inner, "[]") || strings.HasPrefix(inner, "map[") {
				return inner
			}
			return "*" + inner
		}
		return "any"
	case ir.KindRef:
		return toGoName(t.RefName)
	case ir.KindEnum:
		// Inline enum — use the first value's type.
		if t.EnumType != "" {
			return scalarGoType(t.EnumType)
		}
		return "string"
	default:
		return "any"
	}
}

func scalarGoType(s string) string {
	switch s {
	case "string":
		return "string"
	case "integer":
		return "int64"
	case "number":
		return "float64"
	case "boolean":
		return "bool"
	case "any":
		return "any"
	default:
		return "any"
	}
}

func toGoName(s string) string {
	if s == "" {
		return ""
	}

	// Clean characters that aren't valid in Go identifiers.
	s = strings.ReplaceAll(s, "[]", "Slice")
	s = strings.ReplaceAll(s, "*", "Ptr")
	s = strings.ReplaceAll(s, "+", "Plus")
	s = strings.ReplaceAll(s, "&", "And")
	s = strings.ReplaceAll(s, "'", "")
	s = strings.ReplaceAll(s, "\"", "")
	s = strings.ReplaceAll(s, "(", "")
	s = strings.ReplaceAll(s, ")", "")
	s = strings.ReplaceAll(s, "/", "_")
	s = strings.ReplaceAll(s, ":", "_")
	s = strings.ReplaceAll(s, "#", "Hash")
	s = strings.ReplaceAll(s, "@", "At")
	s = strings.ReplaceAll(s, "$", "")
	s = strings.ReplaceAll(s, "<=", "Lte")
	s = strings.ReplaceAll(s, ">=", "Gte")
	s = strings.ReplaceAll(s, "<", "Lt")
	s = strings.ReplaceAll(s, ">", "Gt")
	s = strings.ReplaceAll(s, "=", "Eq")
	s = strings.ReplaceAll(s, "!", "Not")
	s = strings.ReplaceAll(s, "~", "")
	s = strings.ReplaceAll(s, "?", "")
	s = strings.ReplaceAll(s, ";", "")
	s = strings.ReplaceAll(s, "%", "Pct")
	s = strings.ReplaceAll(s, "^", "")
	s = strings.ReplaceAll(s, "`", "")

	parts := strings.FieldsFunc(s, func(r rune) bool {
		return r == '_' || r == '-' || r == '.' || r == '[' || r == ']' || r == ' ' || r == ','
	})

	var result0 strings.Builder
	for _, part := range parts {
		if len(part) == 0 {
			continue
		}
		// Apply common Go capitalizations.
		upper := strings.ToUpper(part)
		switch upper {
		case "ID", "URL", "API", "HTTP", "HTTPS", "JSON", "XML", "HTML", "CSS", "JS",
			"SQL", "SSH", "TCP", "UDP", "IP", "DNS", "TLS", "SSL", "EOF", "UUID":
			result0.WriteString(upper)
		default:
			runes := []rune(part)
			runes[0] = unicode.ToUpper(runes[0])
			result0.WriteString(string(runes))
		}
	}

	result := result0.String()

	// Ensure doesn't start with a digit.
	if len(result) > 0 && result[0] >= '0' && result[0] <= '9' {
		result = "N" + result
	}

	return result
}

func cleanComment(s string) string {
	s = strings.TrimSpace(s)
	s = strings.ReplaceAll(s, "`", "'")
	s = strings.ReplaceAll(s, "\n", "\n// ")
	return s
}

// ImportFromFile is a convenience function that reads a JSON Schema file,
// generates Go code, and writes it to the output path.
func ImportFromFile(schemaPath, pkg, outputPath string) error {
	return ImportFromFileWithConfig(schemaPath, outputPath, Config{Package: pkg})
}

// ImportFromFileWithConfig reads a JSON Schema, applies config, generates
// Go code, and writes it to the output path.
func ImportFromFileWithConfig(schemaPath, outputPath string, cfg Config) error {
	code, err := ImportWithConfig(schemaPath, cfg)
	if err != nil {
		return err
	}

	// Read schema to count types for reporting.
	data, _ := os.ReadFile(schemaPath)
	var doc struct {
		Defs map[string]json.RawMessage `json:"$defs"`
	}
	_ = json.Unmarshal(data, &doc)

	if err := os.WriteFile(outputPath, []byte(code), 0644); err != nil {
		return fmt.Errorf("write output: %w", err)
	}

	fmt.Fprintf(os.Stderr, "✓ imported %d types → %s (%d bytes)\n", len(doc.Defs), outputPath, len(code))
	return nil
}

// extractInlineEnums finds struct fields with inline enum types and
// extracts them as named types in the package.
// Also extracts inline unions (oneOf/anyOf) as named sealed interfaces.
func extractInlineEnums(pkg *ir.Package) {
	for _, name := range pkg.Order {
		t := pkg.Types[name]
		if t.Kind != ir.KindStruct {
			continue
		}
		for i, f := range t.Fields {
			if f.Type.Inline == nil {
				continue
			}
			inline := f.Type.Inline

			// Extract inline enums.
			if inline.Kind == ir.KindEnum && len(inline.EnumValues) > 0 {
				typeName := ""
				for _, c := range inline.Constraints {
					if c.Keyword == "title" {
						if s, ok := c.Value.(string); ok {
							typeName = s
						}
					}
				}
				if typeName == "" {
					typeName = name + toGoName(f.JSONName)
				}

				// Skip if already exists.
				if _, exists := pkg.Types[typeName]; exists {
					t.Fields[i].Type = ir.TypeRef{Name: typeName}
					continue
				}

				var cleanConstraints []ir.Constraint
				for _, c := range inline.Constraints {
					if c.Keyword != "title" {
						cleanConstraints = append(cleanConstraints, c)
					}
				}

				enumType := &ir.Type{
					Name:        typeName,
					Kind:        ir.KindEnum,
					EnumType:    inline.EnumType,
					EnumValues:  inline.EnumValues,
					Description: inline.Description,
					Constraints: cleanConstraints,
				}
				pkg.Add(enumType)
				t.Fields[i].Type = ir.TypeRef{Name: typeName}
				continue
			}

			// Single-variant union → use the variant type directly (likely nullable ref).
			if inline.Kind == ir.KindUnion && len(inline.Variants) == 1 {
				v := inline.Variants[0]
				if v.TypeRef.Name != "" {
					t.Fields[i].Type = ir.TypeRef{Name: v.TypeRef.Name}
				}
				continue
			}

			// Extract inline unions as sealed interfaces.
			if inline.Kind == ir.KindUnion && len(inline.Variants) > 1 {
				typeName := name + toGoName(f.JSONName)
				if _, exists := pkg.Types[typeName]; !exists {
					unionType := &ir.Type{
						Name:          typeName,
						Kind:          ir.KindUnion,
						Description:   inline.Description,
						Discriminator: inline.Discriminator,
						Variants:      inline.Variants,
					}
					pkg.Add(unionType)
				}
				t.Fields[i].Type = ir.TypeRef{Name: typeName}
				continue
			}

			// Extract inline objects as named struct types.
			if inline.Kind == ir.KindStruct && len(inline.Fields) > 0 {
				typeName := name + toGoName(f.JSONName)
				if _, exists := pkg.Types[typeName]; !exists {
					inline.Name = typeName
					pkg.Add(inline)
				}
				t.Fields[i].Type = ir.TypeRef{Name: typeName}
				continue
			}
		}
	}
}
