// Package importer generates Go structs from JSON Schema, preserving
// constraints in jsonschema:"..." tags and generating sealed interfaces
// for oneOf/anyOf unions.
//
// This replaces go-jsonschema in the compschema pipeline with a generator
// that produces Go types that round-trip perfectly through compschema generate.
package importer

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
	"unicode"

	"github.com/codewandler/compschema/internal/ir"
	"github.com/codewandler/compschema/internal/jsonschema2ir"
)

// Import reads a JSON Schema file and generates Go source code.
func Import(schemaPath, pkg string) (string, error) {
	irPkg, err := jsonschema2ir.Parse(schemaPath)
	if err != nil {
		return "", fmt.Errorf("parse schema: %w", err)
	}
	irPkg.Name = pkg

	return GenerateGo(irPkg), nil
}

// ImportBytes reads JSON Schema bytes and generates Go source code.
func ImportBytes(data []byte, pkg string) (string, error) {
	irPkg, err := jsonschema2ir.ParseBytes(data)
	if err != nil {
		return "", fmt.Errorf("parse schema: %w", err)
	}
	irPkg.Name = pkg

	return GenerateGo(irPkg), nil
}

// GenerateGo produces Go source code from an IR package.
func GenerateGo(pkg *ir.Package) string {
	// Post-process: extract inline enums with names (from title) into top-level types.
	extractInlineEnums(pkg)

	var b strings.Builder

	b.WriteString("// Code generated by compschema import. DO NOT EDIT.\n\n")
	b.WriteString(fmt.Sprintf("package %s\n", pkg.Name))

	// Collect all types to emit, sorted for deterministic output.
	names := make([]string, 0, len(pkg.Types))
	for _, n := range pkg.Order {
		names = append(names, n)
	}
	sort.Strings(names)

	for _, name := range names {
		t := pkg.Types[name]
		b.WriteString("\n")
		emitType(&b, name, t, pkg)
	}

	return b.String()
}

func emitType(b *strings.Builder, name string, t *ir.Type, pkg *ir.Package) {
	goName := toGoName(name)

	switch t.Kind {
	case ir.KindStruct:
		emitStruct(b, goName, t, pkg)

	case ir.KindEnum:
		emitEnum(b, goName, t)

	case ir.KindUnion:
		emitUnion(b, goName, t, pkg)

	case ir.KindScalar:
		if t.Description != "" {
			b.WriteString(fmt.Sprintf("// %s %s\n", goName, cleanComment(t.Description)))
		}
		b.WriteString(fmt.Sprintf("type %s %s\n", goName, scalarGoType(t.ScalarType)))

	case ir.KindList:
		elemType := "any"
		if t.Items != nil {
			elemType = typeRefGoType(t.Items, pkg)
		}
		if t.Description != "" {
			b.WriteString(fmt.Sprintf("// %s %s\n", goName, cleanComment(t.Description)))
		}
		b.WriteString(fmt.Sprintf("type %s []%s\n", goName, elemType))

	case ir.KindMap:
		valType := "any"
		if t.MapValue != nil {
			valType = typeRefGoType(t.MapValue, pkg)
		}
		if t.Description != "" {
			b.WriteString(fmt.Sprintf("// %s %s\n", goName, cleanComment(t.Description)))
		}
		b.WriteString(fmt.Sprintf("type %s map[string]%s\n", goName, valType))

	case ir.KindNullable:
		if t.Inner != nil {
			innerType := typeRefGoType(t.Inner, pkg)
			b.WriteString(fmt.Sprintf("type %s = *%s\n", goName, innerType))
		}
	}
}

func emitStruct(b *strings.Builder, goName string, t *ir.Type, pkg *ir.Package) {
	if t.Description != "" {
		b.WriteString(fmt.Sprintf("// %s %s\n", goName, cleanComment(t.Description)))
	}
	b.WriteString(fmt.Sprintf("type %s struct {\n", goName))

	for _, f := range t.Fields {
		fieldGoName := toGoName(f.JSONName)
		fieldType := typeRefGoType(&f.Type, pkg)

		// Add nullable wrapper for non-required fields that aren't already pointers.
		if !f.Required && !strings.HasPrefix(fieldType, "*") && !strings.HasPrefix(fieldType, "[]") && !strings.HasPrefix(fieldType, "map[") {
			fieldType = "*" + fieldType
		}

		// Build tags.
		jsonTag := f.JSONName
		if !f.Required {
			jsonTag += ",omitempty"
		}

		tags := fmt.Sprintf("`json:%q", jsonTag)

		// Build jsonschema tag from constraints + description.
		jsTagParts := buildJSONSchemaTag(f.Constraints, f.Description)
		if jsTagParts != "" {
			tags += fmt.Sprintf(" jsonschema:%q", jsTagParts)
		}
		tags += "`"

		// Field comment.
		if f.Description != "" {
			b.WriteString(fmt.Sprintf("\t// %s\n", cleanComment(f.Description)))
		}
		b.WriteString(fmt.Sprintf("\t%s %s %s\n", fieldGoName, fieldType, tags))
	}

	b.WriteString("}\n")
}

func emitEnum(b *strings.Builder, goName string, t *ir.Type) {
	if t.Description != "" {
		b.WriteString(fmt.Sprintf("// %s %s\n", goName, cleanComment(t.Description)))
	}
	b.WriteString(fmt.Sprintf("type %s %s\n\n", goName, scalarGoType(t.EnumType)))

	b.WriteString("const (\n")
	for _, v := range t.EnumValues {
		constName := goName + toGoName(fmt.Sprintf("%v", v))
		b.WriteString(fmt.Sprintf("\t%s %s = %q\n", constName, goName, fmt.Sprintf("%v", v)))
	}
	b.WriteString(")\n")
}

func emitUnion(b *strings.Builder, goName string, t *ir.Type, pkg *ir.Package) {
	marker := fmt.Sprintf("is%s", goName)

	if t.Description != "" {
		b.WriteString(fmt.Sprintf("// %s %s\n", goName, cleanComment(t.Description)))
	}
	if t.Discriminator != "" {
		b.WriteString(fmt.Sprintf("// Discriminated by %q field.\n", t.Discriminator))
	}

	// Interface.
	b.WriteString(fmt.Sprintf("//\n//compschema:generate\ntype %s interface {\n\t%s()\n}\n\n", goName, marker))

	// Marker methods.
	for _, v := range t.Variants {
		vName := toGoName(v.Name)
		if vName == "" {
			continue
		}
		// Check if the variant type can have methods.
		canHaveMethods := true
		if v.TypeRef.Name != "" {
			if vt, ok := pkg.Types[v.TypeRef.Name]; ok {
				if vt.Kind == ir.KindMap || vt.Kind == ir.KindList ||
					(vt.Kind == ir.KindScalar && vt.ScalarType == "any") ||
					vt.Kind == ir.KindUnion {
					canHaveMethods = false
				}
			}
		} else if v.TypeRef.Inline != nil {
			if v.TypeRef.Inline.Kind == ir.KindMap || v.TypeRef.Inline.Kind == ir.KindScalar {
				canHaveMethods = false
			}
		}
		if !canHaveMethods {
			b.WriteString(fmt.Sprintf("// Note: %s cannot implement %s\n", vName, goName))
			continue
		}
		b.WriteString(fmt.Sprintf("func (*%s) %s() {}\n", vName, marker))
	}
}

func buildJSONSchemaTag(constraints []ir.Constraint, description string) string {
	var parts []string

	for _, c := range constraints {
		switch c.Keyword {
		case "title", "format":
			parts = append(parts, fmt.Sprintf("%s=%v", c.Keyword, sanitizeTagValue(fmt.Sprintf("%v", c.Value))))
		case "minimum", "maximum", "exclusiveMinimum", "exclusiveMaximum", "multipleOf":
			parts = append(parts, fmt.Sprintf("%s=%v", c.Keyword, c.Value))
		case "minLength", "maxLength", "pattern":
			parts = append(parts, fmt.Sprintf("%s=%v", c.Keyword, c.Value))
		case "minItems", "maxItems":
			parts = append(parts, fmt.Sprintf("%s=%v", c.Keyword, c.Value))
		case "const":
			parts = append(parts, fmt.Sprintf("const=%v", sanitizeTagValue(fmt.Sprintf("%v", c.Value))))
		case "uniqueItems", "readOnly", "writeOnly", "deprecated":
			if v, ok := c.Value.(bool); ok && v {
				parts = append(parts, c.Keyword)
			}
		}
	}

	if description != "" {
		desc := sanitizeTagValue(description)
		parts = append(parts, "description="+desc)
	}

	return strings.Join(parts, ",")
}

// sanitizeTagValue removes backticks and normalizes whitespace for struct tags.
func sanitizeTagValue(s string) string {
	s = strings.ReplaceAll(s, "`", "'")
	s = strings.ReplaceAll(s, "\n", " ")
	s = strings.Join(strings.Fields(s), " ")
	return s
}

func typeRefGoType(ref *ir.TypeRef, pkg *ir.Package) string {
	if ref.Name != "" {
		return toGoName(ref.Name)
	}
	if ref.Inline == nil {
		return "any"
	}
	t := ref.Inline
	switch t.Kind {
	case ir.KindScalar:
		return scalarGoType(t.ScalarType)
	case ir.KindList:
		elem := "any"
		if t.Items != nil {
			elem = typeRefGoType(t.Items, pkg)
		}
		return "[]" + elem
	case ir.KindMap:
		val := "any"
		if t.MapValue != nil {
			val = typeRefGoType(t.MapValue, pkg)
		}
		return "map[string]" + val
	case ir.KindNullable:
		if t.Inner != nil {
			inner := typeRefGoType(t.Inner, pkg)
			if strings.HasPrefix(inner, "*") || strings.HasPrefix(inner, "[]") || strings.HasPrefix(inner, "map[") {
				return inner
			}
			return "*" + inner
		}
		return "any"
	case ir.KindRef:
		return toGoName(t.RefName)
	case ir.KindEnum:
		// Inline enum — use the first value's type.
		if t.EnumType != "" {
			return scalarGoType(t.EnumType)
		}
		return "string"
	default:
		return "any"
	}
}

func scalarGoType(s string) string {
	switch s {
	case "string":
		return "string"
	case "integer":
		return "int64"
	case "number":
		return "float64"
	case "boolean":
		return "bool"
	case "any":
		return "any"
	default:
		return "any"
	}
}

func toGoName(s string) string {
	if s == "" {
		return ""
	}

	// Handle JSON names like "file_id" → "FileID"
	parts := strings.FieldsFunc(s, func(r rune) bool {
		return r == '_' || r == '-' || r == '.'
	})

	var result strings.Builder
	for _, part := range parts {
		if len(part) == 0 {
			continue
		}
		// Apply common Go capitalizations.
		upper := strings.ToUpper(part)
		switch upper {
		case "ID", "URL", "API", "HTTP", "HTTPS", "JSON", "XML", "HTML", "CSS", "JS",
			"SQL", "SSH", "TCP", "UDP", "IP", "DNS", "TLS", "SSL", "EOF", "UUID":
			result.WriteString(upper)
		default:
			runes := []rune(part)
			runes[0] = unicode.ToUpper(runes[0])
			result.WriteString(string(runes))
		}
	}

	return result.String()
}

func cleanComment(s string) string {
	s = strings.TrimSpace(s)
	s = strings.ReplaceAll(s, "`", "'")
	s = strings.ReplaceAll(s, "\n", "\n// ")
	return s
}

// ImportFromFile is a convenience function that reads a JSON Schema file,
// generates Go code, and writes it to the output path.
func ImportFromFile(schemaPath, pkg, outputPath string) error {
	code, err := Import(schemaPath, pkg)
	if err != nil {
		return err
	}

	// Read schema to count types for reporting.
	data, _ := os.ReadFile(schemaPath)
	var doc struct {
		Defs map[string]json.RawMessage `json:"$defs"`
	}
	json.Unmarshal(data, &doc)

	if err := os.WriteFile(outputPath, []byte(code), 0644); err != nil {
		return fmt.Errorf("write output: %w", err)
	}

	fmt.Fprintf(os.Stderr, "✓ imported %d types → %s (%d bytes)\n", len(doc.Defs), outputPath, len(code))
	return nil
}

// extractInlineEnums finds struct fields with inline enum types and
// extracts them as named types in the package.
func extractInlineEnums(pkg *ir.Package) {
	for _, name := range pkg.Order {
		t := pkg.Types[name]
		if t.Kind != ir.KindStruct {
			continue
		}
		for i, f := range t.Fields {
			if f.Type.Inline == nil {
				continue
			}
			inline := f.Type.Inline
			if inline.Kind != ir.KindEnum || len(inline.EnumValues) == 0 {
				continue
			}

			// Find a name: from title constraint, or generate from struct+field.
			typeName := ""
			for _, c := range inline.Constraints {
				if c.Keyword == "title" {
					if s, ok := c.Value.(string); ok {
						typeName = s
					}
				}
			}
			if typeName == "" {
				typeName = name + toGoName(f.JSONName)
			}

			// Remove title from constraints (it becomes the type name).
			var cleanConstraints []ir.Constraint
			for _, c := range inline.Constraints {
				if c.Keyword != "title" {
					cleanConstraints = append(cleanConstraints, c)
				}
			}

			// Create the named enum type.
			enumType := &ir.Type{
				Name:        typeName,
				Kind:        ir.KindEnum,
				EnumType:    inline.EnumType,
				EnumValues:  inline.EnumValues,
				Description: inline.Description,
				Constraints: cleanConstraints,
			}
			pkg.Add(enumType)

			// Replace inline type with reference.
			t.Fields[i].Type = ir.TypeRef{Name: typeName}
		}
	}
}
