// Code generated by compschema. DO NOT EDIT.

package config

import (
	_ "embed"
	"encoding/json"
	"sync"

	"github.com/santhosh-tekuri/jsonschema/v6"
)

//go:embed schema.gen.json
var compschemaJSON []byte

var compschemaDefCache sync.Map

func compschemaDefBytes(name string) []byte {
	if v, ok := compschemaDefCache.Load(name); ok {
		return v.([]byte)
	}
	var full struct {
		Defs map[string]json.RawMessage `json:"$defs"`
	}
	json.Unmarshal(compschemaJSON, &full)
	b := full.Defs[name]
	compschemaDefCache.Store(name, []byte(b))
	return b
}

var compschemaValidators sync.Map

func compschemaValidator(name string) *jsonschema.Schema {
	if v, ok := compschemaValidators.Load(name); ok {
		return v.(*jsonschema.Schema)
	}
	c := jsonschema.NewCompiler()
	var doc any
	if err := json.Unmarshal(compschemaJSON, &doc); err != nil {
		panic("compschema: " + err.Error())
	}
	if err := c.AddResource("schema.json", doc); err != nil {
		panic("compschema: " + err.Error())
	}
	sch, err := c.Compile("schema.json#/$defs/" + name)
	if err != nil {
		panic("compschema: " + err.Error())
	}
	compschemaValidators.Store(name, sch)
	return sch
}

// JSONSchemaBytes returns the JSON Schema definition for Action.
func (Action) JSONSchemaBytes() []byte { return compschemaDefBytes("Action") }

// Validate checks whether raw JSON conforms to the Action schema.
func (Action) Validate(data []byte) error {
	sch := compschemaValidator("Action")
	var v any
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	return sch.Validate(v)
}

// DecodeAction validates and unmarshals JSON into a Action.
func DecodeAction(data []byte) (Action, error) {
	var zero Action
	if err := zero.Validate(data); err != nil {
		return Action{}, err
	}
	var result Action
	if err := json.Unmarshal(data, &result); err != nil {
		return Action{}, err
	}
	return result, nil
}

// JSONSchemaBytes returns the JSON Schema definition for File.
func (File) JSONSchemaBytes() []byte { return compschemaDefBytes("File") }

// Validate checks whether raw JSON conforms to the File schema.
func (File) Validate(data []byte) error {
	sch := compschemaValidator("File")
	var v any
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	return sch.Validate(v)
}

// DecodeFile validates and unmarshals JSON into a File.
func DecodeFile(data []byte) (File, error) {
	var zero File
	if err := zero.Validate(data); err != nil {
		return File{}, err
	}
	var result File
	if err := json.Unmarshal(data, &result); err != nil {
		return File{}, err
	}
	return result, nil
}

