// Code generated by compschema. DO NOT EDIT.

package config

import (
	"encoding/json"
	"testing"
)

func TestCompschema_SchemaIsValidJSON(t *testing.T) {
	var v any
	if err := json.Unmarshal(compschemaJSON, &v); err != nil {
		t.Fatalf("schema.gen.json is not valid JSON: %v", err)
	}
}

func TestCompschema_Action_JSONSchemaBytes(t *testing.T) {
	b := (Action{}).JSONSchemaBytes()
	if len(b) == 0 {
		t.Fatal("JSONSchemaBytes returned empty")
	}
	var v any
	if err := json.Unmarshal(b, &v); err != nil {
		t.Fatalf("JSONSchemaBytes is not valid JSON: %v", err)
	}
}

func TestCompschema_Action_ValidateRejectsInvalidJSON(t *testing.T) {
	err := (Action{}).Validate([]byte(`{not json}`))
	if err == nil {
		t.Fatal("Validate should reject invalid JSON")
	}
}

func TestCompschema_Action_ValidateRejectsWrongType(t *testing.T) {
	err := (Action{}).Validate([]byte(`"a string"`))
	if err == nil {
		t.Fatal("Action.Validate should reject a string for an object type")
	}
}

func TestCompschema_Action_ValidateRejectsEmpty(t *testing.T) {
	err := (Action{}).Validate([]byte(`{}`))
	if err == nil {
		t.Fatal("Action.Validate({}) should fail (has required fields)")
	}
}

func TestCompschema_Action_RoundTrip(t *testing.T) {
	data := []byte(`{"action":""}`)
	result, err := DecodeAction(data)
	if err != nil {
		t.Fatalf("Decode: %v", err)
	}
	reencoded, err := json.Marshal(result)
	if err != nil {
		t.Fatalf("re-marshal: %v", err)
	}
	_ = reencoded // round-trip succeeded
}

func TestCompschema_File_JSONSchemaBytes(t *testing.T) {
	b := (File{}).JSONSchemaBytes()
	if len(b) == 0 {
		t.Fatal("JSONSchemaBytes returned empty")
	}
	var v any
	if err := json.Unmarshal(b, &v); err != nil {
		t.Fatalf("JSONSchemaBytes is not valid JSON: %v", err)
	}
}

func TestCompschema_File_ValidateRejectsInvalidJSON(t *testing.T) {
	err := (File{}).Validate([]byte(`{not json}`))
	if err == nil {
		t.Fatal("Validate should reject invalid JSON")
	}
}

func TestCompschema_File_ValidateRejectsWrongType(t *testing.T) {
	err := (File{}).Validate([]byte(`"a string"`))
	if err == nil {
		t.Fatal("File.Validate should reject a string for an object type")
	}
}

func TestCompschema_File_ValidateRejectsEmpty(t *testing.T) {
	err := (File{}).Validate([]byte(`{}`))
	if err == nil {
		t.Fatal("File.Validate({}) should fail (has required fields)")
	}
}

func TestCompschema_File_RoundTrip(t *testing.T) {
	data := []byte(`{"pipelines":{}}`)
	result, err := DecodeFile(data)
	if err != nil {
		t.Fatalf("Decode: %v", err)
	}
	reencoded, err := json.Marshal(result)
	if err != nil {
		t.Fatalf("re-marshal: %v", err)
	}
	_ = reencoded // round-trip succeeded
}

