// Code generated by compschema. DO NOT EDIT.

package basic

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"sync"

	"github.com/santhosh-tekuri/jsonschema/v6"
)

//go:embed schema.gen.json
var compschemaJSON []byte

var compschemaDefCache sync.Map

func compschemaDefBytes(name string) json.RawMessage {
	if v, ok := compschemaDefCache.Load(name); ok {
		return v.(json.RawMessage)
	}
	var full struct {
		Defs map[string]json.RawMessage `json:"$defs"`
	}
	json.Unmarshal(compschemaJSON, &full)
	b := full.Defs[name]
	compschemaDefCache.Store(name, b)
	return b
}

var compschemaValidators sync.Map

func compschemaValidator(name string) *jsonschema.Schema {
	if v, ok := compschemaValidators.Load(name); ok {
		return v.(*jsonschema.Schema)
	}
	c := jsonschema.NewCompiler()
	var doc any
	if err := json.Unmarshal(compschemaJSON, &doc); err != nil {
		panic("compschema: " + err.Error())
	}
	if err := c.AddResource("schema.json", doc); err != nil {
		panic("compschema: " + err.Error())
	}
	sch, err := c.Compile("schema.json#/$defs/" + name)
	if err != nil {
		panic("compschema: " + err.Error())
	}
	compschemaValidators.Store(name, sch)
	return sch
}

// JSONSchemaBytes returns the JSON Schema definition for Circle.
func (Circle) JSONSchemaBytes() json.RawMessage { return compschemaDefBytes("Circle") }

// Validate checks whether raw JSON conforms to the Circle schema.
func (Circle) Validate(data []byte) error {
	sch := compschemaValidator("Circle")
	var v any
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	return sch.Validate(v)
}

// DecodeCircle validates and unmarshals JSON into a Circle.
func DecodeCircle(data []byte) (Circle, error) {
	var zero Circle
	if err := zero.Validate(data); err != nil {
		return Circle{}, err
	}
	var result Circle
	if err := json.Unmarshal(data, &result); err != nil {
		return Circle{}, err
	}
	return result, nil
}

// JSONSchemaBytes returns the JSON Schema definition for LineItem.
func (LineItem) JSONSchemaBytes() json.RawMessage { return compschemaDefBytes("LineItem") }

// Validate checks whether raw JSON conforms to the LineItem schema.
func (LineItem) Validate(data []byte) error {
	sch := compschemaValidator("LineItem")
	var v any
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	return sch.Validate(v)
}

// DecodeLineItem validates and unmarshals JSON into a LineItem.
func DecodeLineItem(data []byte) (LineItem, error) {
	var zero LineItem
	if err := zero.Validate(data); err != nil {
		return LineItem{}, err
	}
	var result LineItem
	if err := json.Unmarshal(data, &result); err != nil {
		return LineItem{}, err
	}
	return result, nil
}

// JSONSchemaBytes returns the JSON Schema definition for Order.
func (Order) JSONSchemaBytes() json.RawMessage { return compschemaDefBytes("Order") }

// Validate checks whether raw JSON conforms to the Order schema.
func (Order) Validate(data []byte) error {
	sch := compschemaValidator("Order")
	var v any
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	return sch.Validate(v)
}

// DecodeOrder validates and unmarshals JSON into a Order.
func DecodeOrder(data []byte) (Order, error) {
	var zero Order
	if err := zero.Validate(data); err != nil {
		return Order{}, err
	}
	var result Order
	if err := json.Unmarshal(data, &result); err != nil {
		return Order{}, err
	}
	return result, nil
}

// JSONSchemaBytes returns the JSON Schema definition for Rectangle.
func (Rectangle) JSONSchemaBytes() json.RawMessage { return compschemaDefBytes("Rectangle") }

// Validate checks whether raw JSON conforms to the Rectangle schema.
func (Rectangle) Validate(data []byte) error {
	sch := compschemaValidator("Rectangle")
	var v any
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	return sch.Validate(v)
}

// DecodeRectangle validates and unmarshals JSON into a Rectangle.
func DecodeRectangle(data []byte) (Rectangle, error) {
	var zero Rectangle
	if err := zero.Validate(data); err != nil {
		return Rectangle{}, err
	}
	var result Rectangle
	if err := json.Unmarshal(data, &result); err != nil {
		return Rectangle{}, err
	}
	return result, nil
}

// ShapeJSONSchemaBytes returns the JSON Schema for the Shape union.
func ShapeJSONSchemaBytes() json.RawMessage { return compschemaDefBytes("Shape") }

// DecodeShape validates and unmarshals JSON into the correct Shape variant.
// Dispatches on the "type" discriminator field.
func DecodeShape(data []byte) (Shape, error) {
	sch := compschemaValidator("Shape")
	var raw any
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}
	if err := sch.Validate(raw); err != nil {
		return nil, err
	}
	var disc struct {
		D string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.D {
	case "circle":
		var val Circle
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	case "rectangle":
		var val Rectangle
		if err := json.Unmarshal(data, &val); err != nil {
			return nil, err
		}
		return &val, nil
	default:
		return nil, fmt.Errorf("unknown type %q for Shape", disc.D)
	}
}

// ShapeAs extracts a variant from a Shape union value, like errors.As.
// Only types whose pointer implements Shape can be used as target (compile-time checked).
//
// Usage:
//
//	var circle Circle
//	if ShapeAs(shape, &circle) {
//		// circle is populated
//	}
func ShapeAs[T any, P interface{ *T; Shape }](v Shape, target *T) bool {
	t, ok := v.(P)
	if ok {
		*target = *t
	}
	return ok
}

