// Code generated by compschema. DO NOT EDIT.

package basic

import (
	"encoding/json"
	"testing"
)

func TestCompschema_SchemaIsValidJSON(t *testing.T) {
	var v any
	if err := json.Unmarshal(compschemaJSON, &v); err != nil {
		t.Fatalf("schema.gen.json is not valid JSON: %v", err)
	}
}

func TestCompschema_Circle_JSONSchemaBytes(t *testing.T) {
	b := (Circle{}).JSONSchemaBytes()
	if len(b) == 0 {
		t.Fatal("JSONSchemaBytes returned empty")
	}
	var v any
	if err := json.Unmarshal(b, &v); err != nil {
		t.Fatalf("JSONSchemaBytes is not valid JSON: %v", err)
	}
}

func TestCompschema_Circle_ValidateRejectsInvalidJSON(t *testing.T) {
	err := (Circle{}).Validate([]byte(`{not json}`))
	if err == nil {
		t.Fatal("Validate should reject invalid JSON")
	}
}

func TestCompschema_Circle_ValidateRejectsWrongType(t *testing.T) {
	err := (Circle{}).Validate([]byte(`"a string"`))
	if err == nil {
		t.Fatal("Circle.Validate should reject a string for an object type")
	}
}

func TestCompschema_Circle_ValidateRejectsEmpty(t *testing.T) {
	err := (Circle{}).Validate([]byte(`{}`))
	if err == nil {
		t.Fatal("Circle.Validate({}) should fail (has required fields)")
	}
}

func TestCompschema_Circle_RoundTrip(t *testing.T) {
	data := []byte(`{"radius":0,"type":"circle"}`)
	result, err := DecodeCircle(data)
	if err != nil {
		t.Fatalf("Decode: %v", err)
	}
	reencoded, err := json.Marshal(result)
	if err != nil {
		t.Fatalf("re-marshal: %v", err)
	}
	_ = reencoded // round-trip succeeded
}

func TestCompschema_LineItem_JSONSchemaBytes(t *testing.T) {
	b := (LineItem{}).JSONSchemaBytes()
	if len(b) == 0 {
		t.Fatal("JSONSchemaBytes returned empty")
	}
	var v any
	if err := json.Unmarshal(b, &v); err != nil {
		t.Fatalf("JSONSchemaBytes is not valid JSON: %v", err)
	}
}

func TestCompschema_LineItem_ValidateRejectsInvalidJSON(t *testing.T) {
	err := (LineItem{}).Validate([]byte(`{not json}`))
	if err == nil {
		t.Fatal("Validate should reject invalid JSON")
	}
}

func TestCompschema_LineItem_ValidateRejectsWrongType(t *testing.T) {
	err := (LineItem{}).Validate([]byte(`"a string"`))
	if err == nil {
		t.Fatal("LineItem.Validate should reject a string for an object type")
	}
}

func TestCompschema_LineItem_ValidateRejectsEmpty(t *testing.T) {
	err := (LineItem{}).Validate([]byte(`{}`))
	if err == nil {
		t.Fatal("LineItem.Validate({}) should fail (has required fields)")
	}
}

func TestCompschema_LineItem_RoundTrip(t *testing.T) {
	data := []byte(`{"qty":1,"sku":"AAA-000"}`)
	result, err := DecodeLineItem(data)
	if err != nil {
		t.Fatalf("Decode: %v", err)
	}
	reencoded, err := json.Marshal(result)
	if err != nil {
		t.Fatalf("re-marshal: %v", err)
	}
	_ = reencoded // round-trip succeeded
}

func TestCompschema_Order_JSONSchemaBytes(t *testing.T) {
	b := (Order{}).JSONSchemaBytes()
	if len(b) == 0 {
		t.Fatal("JSONSchemaBytes returned empty")
	}
	var v any
	if err := json.Unmarshal(b, &v); err != nil {
		t.Fatalf("JSONSchemaBytes is not valid JSON: %v", err)
	}
}

func TestCompschema_Order_ValidateRejectsInvalidJSON(t *testing.T) {
	err := (Order{}).Validate([]byte(`{not json}`))
	if err == nil {
		t.Fatal("Validate should reject invalid JSON")
	}
}

func TestCompschema_Order_ValidateRejectsWrongType(t *testing.T) {
	err := (Order{}).Validate([]byte(`"a string"`))
	if err == nil {
		t.Fatal("Order.Validate should reject a string for an object type")
	}
}

func TestCompschema_Order_ValidateRejectsEmpty(t *testing.T) {
	err := (Order{}).Validate([]byte(`{}`))
	if err == nil {
		t.Fatal("Order.Validate({}) should fail (has required fields)")
	}
}

func TestCompschema_Order_RoundTrip(t *testing.T) {
	data := []byte(`{"id":"","items":[{"qty":1,"sku":"AAA-000"}],"status":"pending"}`)
	result, err := DecodeOrder(data)
	if err != nil {
		t.Fatalf("Decode: %v", err)
	}
	reencoded, err := json.Marshal(result)
	if err != nil {
		t.Fatalf("re-marshal: %v", err)
	}
	_ = reencoded // round-trip succeeded
}

func TestCompschema_Rectangle_JSONSchemaBytes(t *testing.T) {
	b := (Rectangle{}).JSONSchemaBytes()
	if len(b) == 0 {
		t.Fatal("JSONSchemaBytes returned empty")
	}
	var v any
	if err := json.Unmarshal(b, &v); err != nil {
		t.Fatalf("JSONSchemaBytes is not valid JSON: %v", err)
	}
}

func TestCompschema_Rectangle_ValidateRejectsInvalidJSON(t *testing.T) {
	err := (Rectangle{}).Validate([]byte(`{not json}`))
	if err == nil {
		t.Fatal("Validate should reject invalid JSON")
	}
}

func TestCompschema_Rectangle_ValidateRejectsWrongType(t *testing.T) {
	err := (Rectangle{}).Validate([]byte(`"a string"`))
	if err == nil {
		t.Fatal("Rectangle.Validate should reject a string for an object type")
	}
}

func TestCompschema_Rectangle_ValidateRejectsEmpty(t *testing.T) {
	err := (Rectangle{}).Validate([]byte(`{}`))
	if err == nil {
		t.Fatal("Rectangle.Validate({}) should fail (has required fields)")
	}
}

func TestCompschema_Rectangle_RoundTrip(t *testing.T) {
	data := []byte(`{"height":0,"type":"rectangle","width":0}`)
	result, err := DecodeRectangle(data)
	if err != nil {
		t.Fatalf("Decode: %v", err)
	}
	reencoded, err := json.Marshal(result)
	if err != nil {
		t.Fatalf("re-marshal: %v", err)
	}
	_ = reencoded // round-trip succeeded
}

func TestCompschema_Shape_JSONSchemaBytes(t *testing.T) {
	b := ShapeJSONSchemaBytes()
	if len(b) == 0 {
		t.Fatal("JSONSchemaBytes returned empty")
	}
	var v any
	if err := json.Unmarshal(b, &v); err != nil {
		t.Fatalf("JSONSchemaBytes is not valid JSON: %v", err)
	}
}

