// Code generated by compschema. DO NOT EDIT.

package basic

import (
	_ "embed"
	"encoding/json"
	"sync"

	"github.com/santhosh-tekuri/jsonschema/v6"
)

//go:embed schema.gen.json
var compschemaJSON []byte

var compschemaDefCache sync.Map

func compschemaDefBytes(name string) []byte {
	if v, ok := compschemaDefCache.Load(name); ok {
		return v.([]byte)
	}
	var full struct {
		Defs map[string]json.RawMessage `json:"$defs"`
	}
	json.Unmarshal(compschemaJSON, &full)
	b := full.Defs[name]
	compschemaDefCache.Store(name, []byte(b))
	return b
}

var compschemaValidators sync.Map

func compschemaValidator(name string) *jsonschema.Schema {
	if v, ok := compschemaValidators.Load(name); ok {
		return v.(*jsonschema.Schema)
	}
	c := jsonschema.NewCompiler()
	var doc any
	if err := json.Unmarshal(compschemaJSON, &doc); err != nil {
		panic("compschema: " + err.Error())
	}
	if err := c.AddResource("schema.json", doc); err != nil {
		panic("compschema: " + err.Error())
	}
	sch, err := c.Compile("schema.json#/$defs/" + name)
	if err != nil {
		panic("compschema: " + err.Error())
	}
	compschemaValidators.Store(name, sch)
	return sch
}

// JSONSchemaBytes returns the JSON Schema definition for LineItem.
func (LineItem) JSONSchemaBytes() []byte { return compschemaDefBytes("LineItem") }

// Validate checks whether raw JSON conforms to the LineItem schema.
func (LineItem) Validate(data []byte) error {
	sch := compschemaValidator("LineItem")
	var v any
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	return sch.Validate(v)
}

// DecodeLineItem validates and unmarshals JSON into a LineItem.
func DecodeLineItem(data []byte) (LineItem, error) {
	var zero LineItem
	if err := zero.Validate(data); err != nil {
		return LineItem{}, err
	}
	var result LineItem
	if err := json.Unmarshal(data, &result); err != nil {
		return LineItem{}, err
	}
	return result, nil
}

// JSONSchemaBytes returns the JSON Schema for OrderStatus.
func (OrderStatus) JSONSchemaBytes() []byte { return compschemaDefBytes("OrderStatus") }

// JSONSchemaBytes returns the JSON Schema definition for Order.
func (Order) JSONSchemaBytes() []byte { return compschemaDefBytes("Order") }

// Validate checks whether raw JSON conforms to the Order schema.
func (Order) Validate(data []byte) error {
	sch := compschemaValidator("Order")
	var v any
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	return sch.Validate(v)
}

// DecodeOrder validates and unmarshals JSON into a Order.
func DecodeOrder(data []byte) (Order, error) {
	var zero Order
	if err := zero.Validate(data); err != nil {
		return Order{}, err
	}
	var result Order
	if err := json.Unmarshal(data, &result); err != nil {
		return Order{}, err
	}
	return result, nil
}

// JSONSchemaBytes returns the JSON Schema definition for Circle.
func (Circle) JSONSchemaBytes() []byte { return compschemaDefBytes("Circle") }

// Validate checks whether raw JSON conforms to the Circle schema.
func (Circle) Validate(data []byte) error {
	sch := compschemaValidator("Circle")
	var v any
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	return sch.Validate(v)
}

// DecodeCircle validates and unmarshals JSON into a Circle.
func DecodeCircle(data []byte) (Circle, error) {
	var zero Circle
	if err := zero.Validate(data); err != nil {
		return Circle{}, err
	}
	var result Circle
	if err := json.Unmarshal(data, &result); err != nil {
		return Circle{}, err
	}
	return result, nil
}

// JSONSchemaBytes returns the JSON Schema definition for Rectangle.
func (Rectangle) JSONSchemaBytes() []byte { return compschemaDefBytes("Rectangle") }

// Validate checks whether raw JSON conforms to the Rectangle schema.
func (Rectangle) Validate(data []byte) error {
	sch := compschemaValidator("Rectangle")
	var v any
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	return sch.Validate(v)
}

// DecodeRectangle validates and unmarshals JSON into a Rectangle.
func DecodeRectangle(data []byte) (Rectangle, error) {
	var zero Rectangle
	if err := zero.Validate(data); err != nil {
		return Rectangle{}, err
	}
	var result Rectangle
	if err := json.Unmarshal(data, &result); err != nil {
		return Rectangle{}, err
	}
	return result, nil
}

// ShapeJSONSchemaBytes returns the JSON Schema for the Shape union.
func ShapeJSONSchemaBytes() []byte { return compschemaDefBytes("Shape") }

